### ISSUE TITLE
32-bit support - "librealmc.so" not found

### ISSUE THREAD

**Issue by AAkira** [realm/realm-kotlin#108]
This error occurs on Android.
I created a new project using this library by watching [this video](https://www.youtube.com/watch?v=m7lkLu2TE8c).

[This](https://github.com/AAkira/realm-kotlin-example/tree/librealmc.so) is the example of a project I tried.
Do you have any solution?

```
 java.lang.UnsatisfiedLinkError: dlopen failed: library "librealmc.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
        at java.lang.System.loadLibrary(System.java:1664)
        at io.realm.interop.RealmInterop.<clinit>(RealmInterop.kt:28)
        at io.realm.RealmConfiguration.<init>(RealmConfiguration.kt:45)
        at io.realm.RealmConfiguration.<init>(RealmConfiguration.kt:39)
        at io.realm.RealmConfiguration$Builder.build(RealmConfiguration.kt:74)
        at com.github.aakira.realmexample.shared.Database$realm$2.invoke(Database.kt:23)
        at com.github.aakira.realmexample.shared.Database$realm$2.invoke(Unknown Source:0)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.github.aakira.realmexample.shared.Database.getRealm(Database.kt:20)
        at com.github.aakira.realmexample.shared.Database.addPerson(Database.kt:29)
        at com.github.aakira.realmexample.androidApp.MainActivity.onCreate(MainActivity.kt:20)
        at android.app.Activity.performCreate(Activity.java:8000)
        at android.app.Activity.performCreate(Activity.java:7984)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

library version: io.realm.kotlin:library:0.0.1-SNAPSHOT
plugin version: io.realm.kotlin:plugin-gradle:0.0.1-SNAPSHOT

**Comment by rorbech** [comment]
@AAkira Thanks for trying it out. We currently only have setup builds for x86_64 both on Android and iOS. 

Have created #72 and #109 to track support on the remaining platforms.

**Comment by AAkira** [comment]
Thank you!
It works.
I hope this project will go well. 😊

**Comment by CarsonRedeye** [comment]
I get this same error when trying to run on a x86_64 emulator.
