### ISSUE TITLE
Flaky test: SyncedRealmTests.customLoggersReceiveSyncLogs

### ISSUE THREAD

**Issue by rorbech** [realm/realm-kotlin#1235]
The `CustomLogCollector` does not seems to be able to filter messages while collecting messages:

```
Error
java.util.ConcurrentModificationException
Stacktrace
java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1043)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:997)
	at io.realm.kotlin.test.mongodb.shared.SyncedRealmTests$customLoggersReceiveSyncLogs$1.invokeSuspend(SyncedRealmTests.kt:1705)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at io.realm.kotlin.internal.platform.CoroutineUtilsSharedJvmKt.runBlocking(CoroutineUtilsSharedJvm.kt:22)
	at io.realm.kotlin.internal.platform.CoroutineUtilsSharedJvmKt.runBlocking$default(CoroutineUtilsSharedJvm.kt:21)
	at io.realm.kotlin.test.mongodb.shared.SyncedRealmTests.customLoggersReceiveSyncLogs(SyncedRealmTests.kt:1276)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:108)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:57)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:39)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:52)
	at jdk.internal.reflect.GeneratedMethodAccessor32.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
Standard Output
HttpClient: REQUEST: http://127.0.0.1:9090/api/admin/v3.0/auth/profile
METHOD: HttpMethod(value=GET)
HttpClient: RESPONSE: 200 OK
METHOD: HttpMethod(value=GET)
FROM: http://127.0.0.1:9090/api/admin/v3.0/auth/profile
HttpClient: REQUEST: http://127.0.0.1:9090/api/admin/v3.0/groups/63cff9e4b69fa48c412bc811/apps
METHOD: HttpMethod(value=GET)
HttpClient: RESPONSE: 200 OK
METHOD: HttpMethod(value=GET)
FROM: http://127.0.0.1:9090/api/admin/v3.0/groups/63cff9e4b69fa48c412bc811/apps
HttpClient: REQUEST:
...[truncated 116789 chars]...
.0.0.1:9090/api/admin/v3.0/groups/63cff9e4b69fa48c412bc811/apps/63cffaf0b69fa48c412bca7b/users/63cffb89b69fa48c412c13fc
HttpClient: REQUEST: http://127.0.0.1:9090/api/admin/v3.0/groups/63cff9e4b69fa48c412bc811/apps/63cffaf0b69fa48c412bca7b/user_registrations/pending_users
METHOD: HttpMethod(value=GET)
HttpClient: RESPONSE: 200 OK
METHOD: HttpMethod(value=GET)
FROM: http://127.0.0.1:9090/api/admin/v3.0/groups/63cff9e4b69fa48c412bc811/apps/63cffaf0b69fa48c412bca7b/user_registrations/pending_users
```

**Comment by cmelchior** [comment]
I can reproduce consistently by modifying the test like this:

```
    @Test
    fun customLoggersReceiveSyncLogs() = runBlocking {
        val customLogger = CustomLogCollector("CUSTOM", LogLevel.DEBUG)
        val section = Random.nextInt()
        val flexApp = TestApp(
            appName = io.realm.kotlin.test.mongodb.TEST_APP_FLEX,
            builder = {
                it.syncRootDirectory(PlatformUtils.createTempDir("flx-sync-"))
                it.log(level = LogLevel.DEBUG, listOf(customLogger))
            }
        )
        val (email, password) = randomEmail() to "password1234"
        val user = flexApp.createUserAndLogIn(email, password)
        val syncConfig = createFlexibleSyncConfig(
            user = user,
            name = "flex.realm",
            initialSubscriptions = { realm: Realm ->
                realm.query<FlexParentObject>("section = $0", section).subscribe()
            }
        )
        Realm.open(syncConfig).use { flexSyncRealm: Realm ->
            flexSyncRealm.writeBlocking {
                copyToRealm(
                    FlexParentObject().apply {
                        name = "local object"
                    }
                )
            }
//            flexSyncRealm.syncSession.uploadAllLocalChanges()
        }
        assertTrue(customLogger.logs.isNotEmpty())
        assertTrue(
            customLogger.logs
                .onEach {
                    delay(100)
                }
                .filter { it.contains("Connection[1]: Negotiated protocol version:") }
                .isNotEmpty()
        )
        flexApp.close()
    }
```

I will create fix.
