### ISSUE TITLE
Unable to open a realm at path issue

### ISSUE THREAD

**Issue by Vitanio** [realm/realm-kotlin#1275]
Hi, 
I'm facing this issue on some users of our android native application (the stack is been retrieved from crashlytics, due to the difficulty to reproduce the issue).

STACK: 

```
Fatal Exception: java.lang.RuntimeException: Unable to resume activity {packageName/MainPageActivity}: io.realm.exceptions.RealmFileException: Unable to open a realm at path '/data/user/0/packageName/files/name.realm': Realm file decryption failed Path:Exception backtrace:
<backtrace not supported on this platform>. (Realm file decryption failed Path: /data/user/0/packageName/files/name.realm
Exception backtrace:
<backtrace not supported on this platform>) (/data/user/0/packageName/files/name.realm) in /tmp/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 107 Kind: ACCESS_ERROR.
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5365)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5431)
       at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:225)
       at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:146)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2571)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8741)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

Caused by io.realm.exceptions.RealmFileException: Unable to open a realm at path '/data/user/0/packageName/files/name.realm': Realm file decryption failed Path:Exception backtrace:
<backtrace not supported on this platform>. (Realm file decryption failed Path: /data/user/0/packageName/files/name.realm
Exception backtrace:
<backtrace not supported on this platform>) (/data/user/0/packageName/files/name.realm) in /tmp/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 107
       at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(OsSharedRealm.java)
       at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:173)
       at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:249)
       at io.realm.BaseRealm.<init>(BaseRealm.java:138)
       at io.realm.BaseRealm.<init>(BaseRealm.java:105)
       at io.realm.Realm.<init>(Realm.java:159)
       at io.realm.Realm.createInstance(Realm.java:495)
       at io.realm.RealmCache.createInstance(RealmCache.java:481)
       at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:448)
       at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:412)
       at io.realm.Realm.getDefaultInstance(Realm.java:403)
       at com.sitael.vending.ui.main_page.home.HomePageFragment.setCurrencySymbol(HomePageFragment.kt:844)
       at com.sitael.vending.ui.main_page.home.HomePageFragment.setupHomePageView(HomePageFragment.kt:621)
       at com.sitael.vending.ui.main_page.home.HomePageFragment.onResume(HomePageFragment.kt:157)
       at androidx.fragment.app.Fragment.performResume(Fragment.java:3071)
       at androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:605)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:285)
       at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1374)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2841)
       at androidx.fragment.app.FragmentManager.dispatchResume(FragmentManager.java:2798)
       at androidx.fragment.app.Fragment.performResume(Fragment.java:3080)
       at androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:605)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:285)
       at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1374)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2841)
       at androidx.fragment.app.FragmentManager.dispatchResume(FragmentManager.java:2798)
       at androidx.fragment.app.FragmentController.dispatchResume(FragmentController.java:284)
       at androidx.fragment.app.FragmentActivity.onResumeFragments(FragmentActivity.java:434)
       at androidx.fragment.app.FragmentActivity.onPostResume(FragmentActivity.java:423)
       at androidx.appcompat.app.AppCompatActivity.onPostResume(AppCompatActivity.java:240)
       at android.app.Activity.performResume(Activity.java:8746)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5338)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5431)
       at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:225)
       at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:146)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2571)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8741)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

```
System information:
Version: Android 13
Rooted: No
Model: Samsung Galaxy S22 Ultra
Realm gradle plugin version: 10.3.1

May i ask you if it's a known issue? The local db seems to be broken somehow. 
This issue leads the app to crash, so i'm wonder if there is a way to avoid this behaviour.

Thank you for your support.
VD

**Comment by cmelchior** [comment]
It crashes because of this: `Realm file decryption failed` which can happen if either the wrong encryption key was used or the file was corrupted somehow (this can e.g. happen if the file is copied around incorrectly)

**Comment by edualonso** [comment]
This issue affects the Java SDK. @Vitano please check the advise given in https://github.com/realm/realm-kotlin/issues/1275#issuecomment-1422394574 is sufficient to fix your problem. Otherwise reopen the issue using [this link](https://github.com/realm/realm-java/issues/new?assignees=&labels=T-Bug&template=bug.yml) instead.

**Comment by appsoft124** [comment]
> Hi, I'm facing this issue on some users of our android native application (the stack is been retrieved from crashlytics, due to the difficulty to reproduce the issue).
> 
> STACK:
> 
> ```
> Fatal Exception: java.lang.RuntimeException: Unable to resume activity {packageName/MainPageActivity}: io.realm.exceptions.RealmFileException: Unable to open a realm at path '/data/user/0/packageName/files/name.realm': Realm file decryption failed Path:Exception backtrace:
> <backtrace not supported on this platform>. (Realm file decryption failed Path: /data/user/0/packageName/files/name.realm
> Exception backtrace:
> <backtrace not supported on this platform>) (/data/user/0/packageName/files/name.realm) in /tmp/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 107 Kind: ACCESS_ERROR.
>        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5365)
>        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5431)
>        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:225)
>        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
>        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:146)
>        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
>        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2571)
>        at android.os.Handler.dispatchMessage(Handler.java:106)
>        at android.os.Looper.loopOnce(Looper.java:226)
>        at android.os.Looper.loop(Looper.java:313)
>        at android.app.ActivityThread.main(ActivityThread.java:8741)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
> 
> Caused by io.realm.exceptions.RealmFileException: Unable to open a realm at path '/data/user/0/packageName/files/name.realm': Realm file decryption failed Path:Exception backtrace:
> <backtrace not supported on this platform>. (Realm file decryption failed Path: /data/user/0/packageName/files/name.realm
> Exception backtrace:
> <backtrace not supported on this platform>) (/data/user/0/packageName/files/name.realm) in /tmp/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 107
>        at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(OsSharedRealm.java)
>        at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:173)
>        at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:249)
>        at io.realm.BaseRealm.<init>(BaseRealm.java:138)
>        at io.realm.BaseRealm.<init>(BaseRealm.java:105)
>        at io.realm.Realm.<init>(Realm.java:159)
>        at io.realm.Realm.createInstance(Realm.java:495)
>        at io.realm.RealmCache.createInstance(RealmCache.java:481)
>        at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:448)
>        at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:412)
>        at io.realm.Realm.getDefaultInstance(Realm.java:403)
>        at com.sitael.vending.ui.main_page.home.HomePageFragment.setCurrencySymbol(HomePageFragment.kt:844)
>        at com.sitael.vending.ui.main_page.home.HomePageFragment.setupHomePageView(HomePageFragment.kt:621)
>        at com.sitael.vending.ui.main_page.home.HomePageFragment.onResume(HomePageFragment.kt:157)
>        at androidx.fragment.app.Fragment.performResume(Fragment.java:3071)
>        at androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:605)
>        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:285)
>        at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
>        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1374)
>        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2841)
>        at androidx.fragment.app.FragmentManager.dispatchResume(FragmentManager.java:2798)
>        at androidx.fragment.app.Fragment.performResume(Fragment.java:3080)
>        at androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:605)
>        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:285)
>        at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
>        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1374)
>        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2841)
>        at androidx.fragment.app.FragmentManager.dispatchResume(FragmentManager.java:2798)
>        at androidx.fragment.app.FragmentController.dispatchResume(FragmentController.java:284)
>        at androidx.fragment.app.FragmentActivity.onResumeFragments(FragmentActivity.java:434)
>        at androidx.fragment.app.FragmentActivity.onPostResume(FragmentActivity.java:423)
>        at androidx.appcompat.app.AppCompatActivity.onPostResume(AppCompatActivity.java:240)
>        at android.app.Activity.performResume(Activity.java:8746)
>        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5338)
>        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5431)
>        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:225)
>        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
>        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:146)
>        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
>        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2571)
>        at android.os.Handler.dispatchMessage(Handler.java:106)
>        at android.os.Looper.loopOnce(Looper.java:226)
>        at android.os.Looper.loop(Looper.java:313)
>        at android.app.ActivityThread.main(ActivityThread.java:8741)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
> ```
> 
> System information: Version: Android 13 Rooted: No Model: Samsung Galaxy S22 Ultra Realm gradle plugin version: 10.3.1
> 
> May i ask you if it's a known issue? The local db seems to be broken somehow. This issue leads the app to crash, so i'm wonder if there is a way to avoid this behaviour.
> 
> Thank you for your support. VD

Have you fix the issue or not >
