### ISSUE TITLE
Migrating primary key from Java SDK

### ISSUE THREAD

**Issue by morand1** [realm/realm-kotlin#1306]
Hi, I'm making migration from the Java to Kotlin SDK. And I'm having a problem with the PrimaryKey. I've created a new model class but still getting exception:
```
java.lang.ExceptionInInitializerError
at java.lang.reflect.Field.get(Native Method)
at kotlin.reflect.jvm.internal.KClassImpl$Data$objectInstance$2.invoke(KClassImpl.kt:117)
at kotlin.reflect.jvm.internal.ReflectProperties$LazyVal.invoke(ReflectProperties.java:63)
at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:32)
at kotlin.reflect.jvm.internal.KClassImpl$Data.getObjectInstance(KClassImpl.kt:108)
at kotlin.reflect.jvm.internal.KClassImpl.getObjectInstance(KClassImpl.kt:242)
at kotlin.reflect.full.KClasses.getCompanionObjectInstance(KClasses.kt:57)
at io.realm.kotlin.internal.platform.RealmObjectKt.realmObjectCompanionOrNull(RealmObject.kt:27)
at io.realm.kotlin.Configuration$SharedBuilder.<init>(Configuration.kt:408)
at io.realm.kotlin.RealmConfiguration$Builder.<init>(RealmConfiguration.kt:51)
```
This is my old Java SDK class:
```
public class MyClass extends RealmObject {

    @PrimaryKey
    @Required
    private String myId;
    private String otherValue;
```
and the new one:
```
class MyClass : RealmObject {
    @PrimaryKey
    val siteId: String = ""
    val otherValue: String? = null
```
I was trying also with ObjectId as primary key but it's not working. What am I doing wrong?

**Comment by cmelchior** [comment]
The properties in the Kotlin model class cannot be `val` since they might be modified in the Realm database, so they need to be `var`.

That said, there are a few cases where it might make sense to allow `val`, the primary key being one of them since it isn't allowed to change. But right now, that isn't supported.

**Comment by morand1** [comment]
Works perfectly with var, thanks!

**Comment by cmelchior** [comment]
We have other issues, i.e. using `var`  for backlinks will result in `Type 'BacklinksDelegate<EmbeddedChild>' has no method 'setValue(Parent, KProperty<*>, RealmResults<EmbeddedChild>)' and thus it cannot serve as a delegate for var (read-write property)`
