### ISSUE TITLE
RealmCoreException([2]: Read-only file system

### ISSUE THREAD

**Issue by xiaoyan159** [realm/realm-kotlin#1332]
### How frequently does the bug occur?

Always

### Description

When I developing Android App with the Realm Kotlin SDK, specify a path to the Realm database through the following code
```
val config = RealmConfiguration.Builder(schema = setOf(Dog::class))
                        .directory(SystemConstant.DBFolder)
                        .name("Test.realm")
                        .build()
```
In the above code, SystemConstant.DBFolder refers to the path of the external storege card. I confirm that the Android program has obtained the write permission of the external storege card

Realm also created some files in the directory, I thought maybe this is a bug? Realm Kotlin does not allow database file creation on external storege cards?

### Stacktrace & log output

```shell
FATAL EXCEPTION: main
                                                                                                    Process: com.navinfo.volvo, PID: 15616
                                                                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.navinfo.volvo/com.navinfo.volvo.ui.MainActivity}: java.lang.IllegalArgumentException: Could not open Realm with the given configuration: path=/storage/emulated/0/Android/data/com.navinfo.volvo/files/log/Test.realm
                                                                                                     name=Test.realm
                                                                                                     maxNumberOfActiveVersions=9223372036854775807
                                                                                                     schemaVersion=0
                                                                                                     schemaMode=RLM_SCHEMA_MODE_AUTOMATIC
                                                                                                     schema=[class com.navinfo.volvo.model.Dog]: RealmCoreException([2]: Read-only file system)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3764)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3938)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:106)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2282)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:211)
                                                                                                    	at android.os.Looper.loop(Looper.java:300)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8258)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
                                                                                                    Caused by: java.lang.IllegalArgumentException: Could not open Realm with the given configuration: path=/storage/emulated/0/Android/data/com.navinfo.volvo/files/log/Test.realm
                                                                                                     name=Test.realm
                                                                                                     maxNumberOfActiveVersions=9223372036854775807
                                                                                                     schemaVersion=0
                                                                                                     schemaMode=RLM_SCHEMA_MODE_AUTOMATIC
                                                                                                     schema=[class com.navinfo.volvo.model.Dog]: RealmCoreException([2]: Read-only file system)
                                                                                                    	at io.realm.kotlin.internal.CoreExceptionConverter.genericRealmCoreExceptionHandler(RealmInteropBridge.kt:165)
                                                                                                    	at io.realm.kotlin.internal.CoreExceptionConverter.convertToPublicException(RealmInteropBridge.kt:137)
                                                                                                    	at io.realm.kotlin.internal.CoreExceptionConverter.convertToPublicException$default(RealmInteropBridge.kt:127)
                                                                                                    	at io.realm.kotlin.internal.RealmImpl$Companion.create$io_realm_kotlin_library(RealmImpl.kt:298)
                                                                                                    	at io.realm.kotlin.Realm$Companion.open(Realm.kt:82)
                                                                                                    	at com.navinfo.volvo.ui.MainActivity$onCreate$1.onGranted(MainActivity.kt:77)
                                                                                                    	at com.hjq.permissions.IPermissionInterceptor.grantedPermissionRequest(IPermissionInterceptor.java:43)
                                                                                                    	at com.hjq.permissions.XXPermissions.request(XXPermissions.java:197)
                                                                                                    	at com.navinfo.volvo.ui.MainActivity.onCreate(MainActivity.kt:61)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8305)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8269)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1374)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3744)
                                                                                                    	... 12 more
                                                                                                    Caused by: io.realm.kotlin.internal.interop.RealmCoreOtherException: [2]: Read-only file system
                                                                                                    	at io.realm.kotlin.internal.interop.CoreErrorUtils.coreErrorAsThrowable(CoreErrorUtils.kt:28)
                                                                                                    	at io.realm.kotlin.internal.interop.realmcJNI.open_realm_with_scheduler(Native Method)
                                                                                                    	at io.realm.kotlin.internal.interop.realmc.open_realm_with_scheduler(realmc.java:1703)
                                                                                                    	at io.realm.kotlin.internal.interop.RealmInterop.realm_open(RealmInterop.kt:193)
                                                                                                    	at io.realm.kotlin.internal.interop.RealmInterop.realm_open$default(RealmInterop.kt:181)
                                                                                                    	at io.realm.kotlin.internal.ConfigurationImpl.openRealm$suspendImpl(ConfigurationImpl.kt:105)
                                                                                                    	at io.realm.kotlin.internal.ConfigurationImpl.openRealm(Unknown Source:0)
                                                                                                    	at io.realm.kotlin.internal.RealmImpl$1.invokeSuspend(RealmImpl.kt:121)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
2023-04-04 16:19:19.729 15616-15616 AndroidRuntime          com.navinfo.volvo                    E  	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
                                                                                                    	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
                                                                                                    	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
                                                                                                    	at io.realm.kotlin.internal.platform.CoroutineUtilsSharedJvmKt.runBlocking(CoroutineUtilsSharedJvm.kt:22)
                                                                                                    	at io.realm.kotlin.internal.platform.CoroutineUtilsSharedJvmKt.runBlocking$default(CoroutineUtilsSharedJvm.kt:21)
                                                                                                    	at io.realm.kotlin.internal.RealmImpl.<init>(RealmImpl.kt:118)
                                                                                                    	at io.realm.kotlin.internal.RealmImpl.<init>(Unknown Source:0)
                                                                                                    	at io.realm.kotlin.internal.RealmImpl$Companion.create$io_realm_kotlin_library(RealmImpl.kt:296)
                                                                                                    	... 21 more
```

### Can you reproduce the bug?

Always

### Reproduction Steps

https://github.com/xiaoyan159/RealmTest/tree/realm

branch: realm

### Version

1.6.1

### What Atlas App Services are you using?

Local Database only

### Are you using encryption?

Yes

### Platform OS and version(s)

Android 12

### Build environment

Android Studio version: 2021.3.1
Android Build Tools version: 30.0.3
Gradle version: 7.4

**Comment by rorbech** [comment]
Hi @xiaoyan159. How did you grant write privileges to the external storage and what API level are you targeting? More recent versions of Android have changed the way you request these permissions: https://developer.android.com/training/data-storage#permissions

Can you try to elaborate a bit on what files are actually created and maybe dump the realm logs after setting the log level with:
```
val config = RealmConfiguration.Builder(schema = setOf(Dog::class))
                        .directory(SystemConstant.DBFolder)
                        .log(LogLevel.DEBUG)
                        .name("Test.realm")
                        .build()
```

**Comment by xiaoyan159** [comment]
I used an open source permission request  framework，yes，I know the changed after Android Api 30+， and the application target Api is 32。
A partial Realm file is now being generated，So this shouldn't be an external storage permission issue，and the log and realm data file image is behind
[Log.txt](https://github.com/realm
![Screenshot_20230406_112711](https://user-images.githubusercontent.com/7743140/230265030-ee538140-4bda-40fd-b8a6-a2711adfffe7.png)
/realm-kotlin/files/11166124/Log.txt)

**Comment by xiaoyan159** [comment]
[Log.txt](https://github.com/realm/realm-kotlin/files/11166147/Log.txt)

**Comment by rorbech** [comment]
@xiaoyan159 It also seems like the actual realm files is in place, so something must clearly be able to write the location. 
How do you get the initial realm file in place? Could it be that the existing realm file is somehow ended up being write protected. Could you inspect the permissions of the existing file.

**Comment by xiaoyan159** [comment]
It's like this, when I don't specify the save location for the realm file and use the following config, the code will not report an error，but the saved file is in the private directory of the app, and I cannot view the file content in the file manager
```
val config = RealmConfiguration.Builder(schema = setOf(Dog::class))
                        .directory(SystemConstant.DBFolder)
                        .log(LogLevel.DEBUG)
                        .name("Test.realm")
                        .build()
```
When I specify the absolute path to the realm file, this path is the system specific external storage card path for the application after Android 10. At this point, the app will report the above error
```
val config = RealmConfiguration.Builder(schema = setOf(Dog::class))
                        .directory(SystemConstant.DBFolder)
                        .log(LogLevel.DEBUG)
                        .name("${SystemConstant.ROOT_PATH}/Test.realm")
                        .build()
```
If using Realm's Java SDK, creating Realm files under the same path will not result in an error,So I think this is a bug in the Kotlin SDK

**Comment by xiaoyan159** [comment]
Here is an example program，https://github.com/xiaoyan159/RealmTest/blob/realm/app/src/main/java/com/navinfo/volvo/ui/MainActivity.kt

Please pay attention to lines 72 to 78 of this file

**Comment by rorbech** [comment]
The `name(...)` should only be used to specify the filename, hence without any directory elements, so you should add all the direcoty elements to the argument of `directory(...)` call. 

The `name(...)` method should throw an `IllegalArgumentException` is the argument contains a path separator. Are you saying that this is not the case? And what is your expanded argument to `name(...)`?

**Comment by xiaoyan159** [comment]
Oh sorry, the name setting should be the file name ("Test. realm"), the directory specifying is ${getExternalFilesDir(null)?.absolutePath}/realm, and the method to obtain the directory is:
```
Log.d("mypath:","${getExternalFilesDir(null)?.absolutePath}/realm")
val config = RealmConfiguration.Builder(schema = setOf(Dog::class))
                        .directory("${getExternalFilesDir(null)?.absolutePath}/realm")
                        .log(io.realm.kotlin.log.LogLevel.DEBUG)
                        .name("Test.realm")
                        .build()
```
mypath is "/storage/emulated/0/Android/data/com.navinfo.volvo/files/realm" in the log

**Comment by cmelchior** [comment]
`getExternalFilesDir` is not support from API 30: https://developer.android.com/about/versions/11/privacy/storage

At that API level, Android added restrictions to the external filesystem that makes it impossible for Realm to directly place our files there. You can copy it back and forth from external storage, but not use it as a place to put a database file while the app is running.

**Comment by xiaoyan159** [comment]
Okay, I understand. In versions of Android 10 and above, the database files should be saved in a private directory. I would like to be able to copy the Realm database files at certain times and use Realm Studio to view the data. As per your suggestion, when this is necessary, perhaps I should call the copyto method to copy from the built-in storage to the external storage card location

**Comment by cmelchior** [comment]
Yes, that would be one way to do it 👍
