### ISSUE TITLE
Allow to delete RealmResults baked by backlinks

### ISSUE THREAD

**Issue by promanowicz** [realm/realm-kotlin#1413]
### Problem

If I try to remove all objects that are in the RealmResult list baked by backlinks
I get 
java.lang.IllegalArgumentException: Cannot delete custom Deleteable objects: ObjectBoundRealmResults
at io.realm.kotlin.internal.InternalDeleteableKt.asInternalDeleteable(InternalDeleteable.kt:36)
at io.realm.kotlin.internal.InternalMutableRealm$DefaultImpls.delete(InternalMutableRealm.kt:63)
at io.realm.kotlin.internal.SuspendableWriter$WriterRealm.delete(SuspendableWriter.kt:51)
...
when doing MutableRealm.delete(realmResults)

### Solution

All elements of backlinked RealmResults are deleted from database when doing MutableRealm.delete(realmResults)

### How important is this improvement for you?

I would like to have it but have a workaround

### Feature would mainly be used with

Local Database only

**Comment by cmelchior** [comment]
Thank you for reporting this. Yes, this is a bug that will be fixed.
