### ISSUE TITLE
Run unit test at commonTest KMM

### ISSUE THREAD

**Issue by ptsiogas** [realm/realm-kotlin#1449]
### How frequently does the bug occur?

Always

### Description

Hello, we have set the exact same classes as in the realm-kotlin example project in order to confirm that we can run unit tests for realm-kotlin.
The project syncs and runs ok but the commonTest unit tests are always failing. We are running the unit tests for android.

```
class ExpressionRepositoryTest {

    @Test
    fun insert() {
        val repository = ExpressionRepository()
        val expression = repository.addExpression("a + b")
        assertEquals("a + b", expression.expressionString)
    }
}

class Expression : RealmObject {
    var expressionString: String = ""
}

class ExpressionRepository {

    val realm: Realm by lazy {
        val configuration = RealmConfiguration.create(schema = setOf(Expression::class))
        Realm.open(configuration)
    }

    fun addExpression(expression: String): Expression {
        return realm.writeBlocking {
            copyToRealm(Expression().apply { expressionString = expression })
        }
    }

    fun expressions(): List<Expression> {
        return realm.query<Expression>().find()
    }

    fun observeChanges(): Flow<List<Expression>> {
        return realm.query<Expression>().asFlow().map { it.list }
    }
}
```

### Stacktrace & log output

```shell
java.lang.ExceptionInInitializerError
	at io.realm.kotlin.RealmConfiguration$Builder.<init>(RealmConfiguration.kt:55)
	at io.realm.kotlin.RealmConfiguration$Companion.create(RealmConfiguration.kt:181)
	at gr.desquared.kmmsharedmodule.ExpressionRepository$realm$2.invoke(ExpressionRepository.kt:16)
	at gr.desquared.kmmsharedmodule.ExpressionRepository$realm$2.invoke(ExpressionRepository.kt:15)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at gr.desquared.kmmsharedmodule.ExpressionRepository.getRealm(ExpressionRepository.kt:15)
	at gr.desquared.kmmsharedmodule.ExpressionRepository.addExpression(ExpressionRepository.kt:21)
	at gr.desquared.kmmsharedmodule.ExpressionRepositoryTest.insert(OrderDataSourceTest.kt:11)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at jdk.proxy2/jdk.proxy2.$Proxy5.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
Caused by: java.lang.NullPointerException: {
        @Suppress("DEP…id.os.Build.CPU_ABI
    } must not be null
	at io.realm.kotlin.internal.platform.SystemUtilsAndroidKt.<clinit>(SystemUtilsAndroid.kt:16)
	... 51 more
```

### Can you reproduce the bug?

Always

### Version

1.9.0

### What Atlas App Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

KMM with Kotlin 1.8.20

### Build environment

Android Studio version: Android Studio Flamingo | 2022.2.1 Patch 2
Android Build Tools version: 7.4.2
Gradle version: 7.5.1

**Comment by clementetb** [comment]
Since version `1.10.0` we support running Android unit tests in the JVM. Could you try upgrading to version >= `1.10.0`?

**Comment by ptsiogas** [comment]
I have tried with the `1.10.0` and I get the stacktrace below:


```
Bad local variable type
Exception Details:
  Location:
    io/realm/kotlin/internal/RealmObjectHelper.setObject$io_realm_kotlin_library$default(Lio/realm/kotlin/internal/RealmObjectHelper;Lio/realm/kotlin/internal/RealmObjectReference;Ljava/lang/String;Lio/realm/kotlin/types/BaseRealmObject;Lio/realm/kotlin/UpdatePolicy;Ljava/util/Map;ILjava/lang/Object;)V @137: aload
  Reason:
    Type long_2nd (current frame, locals[8]) is not assignable to reference type
  Current Frame:
    bci: @137
    flags: { }
    locals: { 'io/realm/kotlin/internal/RealmObjectHelper', 'io/realm/kotlin/internal/RealmObjectReference', 'java/lang/String', 'io/realm/kotlin/types/BaseRealmObject', 'io/realm/kotlin/UpdatePolicy', 'java/util/Map', integer, long, long_2nd, top, 'io/realm/kotlin/internal/RealmObjectHelper', integer }
    stack: { }
  Bytecode:
    0000000: b807 8b3a 0815 0610 087e 9a00 0c19 0810
    0000010: 1404 54a7 000e b200 983a 0419 0810 1504
    0000020: 5415 0610 107e 9a00 0c19 0810 1604 54a7
    0000030: 001b 1908 1017 0454 bb00 9a59 b700 9bc0
    0000040: 0091 3a05 1908 1018 0454 2b12 11b8 0017
    0000050: 2c12 19b8 0017 1904 121b b800 1719 0512
    0000060: 1db8 0017 0336 0619 0810 1904 542b b600
    0000070: 2219 0810 1a04 542b 2cb6 0026 b900 2c01
    0000080: 0037 072a 3a0a 0336 0b19 0810 1b04 542b
    0000090: b600 2219 0810 1c04 542b b600 303a 0c2b
    00000a0: b600 343a 0d03 360e 0336 0f2d 59c6 006d
    00000b0: 3a10 0336 1119 0810 1d04 542d b800 3a3a
    00000c0: 1219 12c6 0036 1908 101e 0454 1912 b600
    00000d0: 3419 0db8 003e 9900 0d2d 1908 101f 0454
    00000e0: a700 30bb 0040 5912 4219 0810 2004 54b7
    00000f0: 0045 1908 1021 0454 bf19 0c19 0db9 004b
    0000100: 0100 2d19 0419 05b8 0051 1908 1022 0454
    0000110: 0019 0810 2304 54a7 000b 5701 1908 1024
    0000120: 0454 3a13 1913 c600 1719 1319 0810 2504
    0000130: 54b8 003a 1908 1026 0454 a700 0a01 1908
    0000140: 1027 0454 003a 1403 360c 0336 0d19 0810
    0000150: 2804 54bb 0053 59b7 0054 c000 563a 0e19
    0000160: 0e3a 0f03 3610 1908 1029 0454 b200 592b
    0000170: 1607 190f 1914 c000 5bb9 005f 0200 b600
    0000180: 63b2 0068 3a0d 1908 102a 0454 190e b900
    0000190: 6b01 0000 0019 0810 2b04 54b1          
  Stackmap Table:
    append_frame(@22,Object[#1933])
    same_frame(@33)
    same_frame(@50)
    same_frame(@74)
    full_frame(@227,{Object[#2],Object[#31],Object[#139],Object[#141],Object[#143],Object[#145],Integer,Long,Object[#2],Integer,Object[#147],Object[#71],Integer,Integer,Object[#141],Integer,Object[#31]},{})
    same_frame(@249)
    same_locals_1_stack_item_frame(@272,Object[#141])
    full_frame(@282,{Object[#2],Object[#31],Object[#139],Object[#141],Object[#143],Object[#145],Integer,Long,Object[#2],Integer,Object[#147],Object[#71],Integer,Integer},{Object[#141]})
    same_locals_1_stack_item_frame(@290,Object[#141])
    full_frame(@317,{Object[#2],Object[#31],Object[#139],Object[#141],Object[#143],Object[#145],Integer,Long,Object[#2],Integer,Object[#147],Object[#71],Integer,Integer,Top,Top,Top,Object[#141]},{})
    same_locals_1_stack_item_frame(@324,Object[#31])

java.lang.VerifyError: Bad local variable type
Exception Details:
  Location:
    io/realm/kotlin/internal/RealmObjectHelper.setObject$io_realm_kotlin_library$default(Lio/realm/kotlin/internal/RealmObjectHelper;Lio/realm/kotlin/internal/RealmObjectReference;Ljava/lang/String;Lio/realm/kotlin/types/BaseRealmObject;Lio/realm/kotlin/UpdatePolicy;Ljava/util/Map;ILjava/lang/Object;)V @137: aload
  Reason:
    Type long_2nd (current frame, locals[8]) is not assignable to reference type
  Current Frame:
    bci: @137
    flags: { }
    locals: { 'io/realm/kotlin/internal/RealmObjectHelper', 'io/realm/kotlin/internal/RealmObjectReference', 'java/lang/String', 'io/realm/kotlin/types/BaseRealmObject', 'io/realm/kotlin/UpdatePolicy', 'java/util/Map', integer, long, long_2nd, top, 'io/realm/kotlin/internal/RealmObjectHelper', integer }
    stack: { }
  Bytecode:
    0000000: b807 8b3a 0815 0610 087e 9a00 0c19 0810
    0000010: 1404 54a7 000e b200 983a 0419 0810 1504
    0000020: 5415 0610 107e 9a00 0c19 0810 1604 54a7
    0000030: 001b 1908 1017 0454 bb00 9a59 b700 9bc0
    0000040: 0091 3a05 1908 1018 0454 2b12 11b8 0017
    0000050: 2c12 19b8 0017 1904 121b b800 1719 0512
    0000060: 1db8 0017 0336 0619 0810 1904 542b b600
    0000070: 2219 0810 1a04 542b 2cb6 0026 b900 2c01
    0000080: 0037 072a 3a0a 0336 0b19 0810 1b04 542b
    0000090: b600 2219 0810 1c04 542b b600 303a 0c2b
    00000a0: b600 343a 0d03 360e 0336 0f2d 59c6 006d
    00000b0: 3a10 0336 1119 0810 1d04 542d b800 3a3a
    00000c0: 1219 12c6 0036 1908 101e 0454 1912 b600
    00000d0: 3419 0db8 003e 9900 0d2d 1908 101f 0454
    00000e0: a700 30bb 0040 5912 4219 0810 2004 54b7
    00000f0: 0045 1908 1021 0454 bf19 0c19 0db9 004b
    0000100: 0100 2d19 0419 05b8 0051 1908 1022 0454
    0000110: 0019 0810 2304 54a7 000b 5701 1908 1024
    0000120: 0454 3a13 1913 c600 1719 1319 0810 2504
    0000130: 54b8 003a 1908 1026 0454 a700 0a01 1908
    0000140: 1027 0454 003a 1403 360c 0336 0d19 0810
    0000150: 2804 54bb 0053 59b7 0054 c000 563a 0e19
    0000160: 0e3a 0f03 3610 1908 1029 0454 b200 592b
    0000170: 1607 190f 1914 c000 5bb9 005f 0200 b600
    0000180: 63b2 0068 3a0d 1908 102a 0454 190e b900
    0000190: 6b01 0000 0019 0810 2b04 54b1          
  Stackmap Table:
    append_frame(@22,Object[#1933])
    same_frame(@33)
    same_frame(@50)
    same_frame(@74)
    full_frame(@227,{Object[#2],Object[#31],Object[#139],Object[#141],Object[#143],Object[#145],Integer,Long,Object[#2],Integer,Object[#147],Object[#71],Integer,Integer,Object[#141],Integer,Object[#31]},{})
    same_frame(@249)
    same_locals_1_stack_item_frame(@272,Object[#141])
    full_frame(@282,{Object[#2],Object[#31],Object[#139],Object[#141],Object[#143],Object[#145],Integer,Long,Object[#2],Integer,Object[#147],Object[#71],Integer,Integer},{Object[#141]})
    same_locals_1_stack_item_frame(@290,Object[#141])
    full_frame(@317,{Object[#2],Object[#31],Object[#139],Object[#141],Object[#143],Object[#145],Integer,Long,Object[#2],Integer,Object[#147],Object[#71],Integer,Integer,Top,Top,Top,Object[#141]},{})
    same_locals_1_stack_item_frame(@324,Object[#31])

	at io.realm.kotlin.internal.RealmUtilsKt.copyToRealm(RealmUtils.kt:215)
	at io.realm.kotlin.internal.RealmUtilsKt.copyToRealm$default(RealmUtils.kt:139)
	at io.realm.kotlin.internal.InternalMutableRealm$DefaultImpls.copyToRealm(InternalMutableRealm.kt:57)
	at io.realm.kotlin.internal.SuspendableWriter$WriterRealm.copyToRealm(SuspendableWriter.kt:52)
	at io.realm.kotlin.MutableRealm$DefaultImpls.copyToRealm$default(MutableRealm.kt:88)
	at gr.desquared.kmmsharedmodule.ExpressionRepository$addExpression$1.invoke(ExpressionRepository.kt:23)
	at gr.desquared.kmmsharedmodule.ExpressionRepository$addExpression$1.invoke(ExpressionRepository.kt:22)
	at io.realm.kotlin.internal.SuspendableWriter$write$2.invokeSuspend(SuspendableWriter.kt:110)
	at _COROUTINE._BOUNDARY._(CoroutineDebugging.kt:46)
	at io.realm.kotlin.internal.RealmImpl$writeBlocking$1.invokeSuspend(RealmImpl.kt:196)
Caused by: java.lang.VerifyError: Bad local variable type
Exception Details:
  Location:
    io/realm/kotlin/internal/RealmObjectHelper.setObject$io_realm_kotlin_library$default(Lio/realm/kotlin/internal/RealmObjectHelper;Lio/realm/kotlin/internal/RealmObjectReference;Ljava/lang/String;Lio/realm/kotlin/types/BaseRealmObject;Lio/realm/kotlin/UpdatePolicy;Ljava/util/Map;ILjava/lang/Object;)V @137: aload
  Reason:
    Type long_2nd (current frame, locals[8]) is not assignable to reference type
  Current Frame:
    bci: @137
    flags: { }
    locals: { 'io/realm/kotlin/internal/RealmObjectHelper', 'io/realm/kotlin/internal/RealmObjectReference', 'java/lang/String', 'io/realm/kotlin/types/BaseRealmObject', 'io/realm/kotlin/UpdatePolicy', 'java/util/Map', integer, long, long_2nd, top, 'io/realm/kotlin/internal/RealmObjectHelper', integer }
    stack: { }
  Bytecode:
    0000000: b807 8b3a 0815 0610 087e 9a00 0c19 0810
    0000010: 1404 54a7 000e b200 983a 0419 0810 1504
    0000020: 5415 0610 107e 9a00 0c19 0810 1604 54a7
    0000030: 001b 1908 1017 0454 bb00 9a59 b700 9bc0
    0000040: 0091 3a05 1908 1018 0454 2b12 11b8 0017
    0000050: 2c12 19b8 0017 1904 121b b800 1719 0512
    0000060: 1db8 0017 0336 0619 0810 1904 542b b600
    0000070: 2219 0810 1a04 542b 2cb6 0026 b900 2c01
    0000080: 0037 072a 3a0a 0336 0b19 0810 1b04 542b
    0000090: b600 2219 0810 1c04 542b b600 303a 0c2b
    00000a0: b600 343a 0d03 360e 0336 0f2d 59c6 006d
    00000b0: 3a10 0336 1119 0810 1d04 542d b800 3a3a
    00000c0: 1219 12c6 0036 1908 101e 0454 1912 b600
    00000d0: 3419 0db8 003e 9900 0d2d 1908 101f 0454
    00000e0: a700 30bb 0040 5912 4219 0810 2004 54b7
    00000f0: 0045 1908 1021 0454 bf19 0c19 0db9 004b
    0000100: 0100 2d19 0419 05b8 0051 1908 1022 0454
    0000110: 0019 0810 2304 54a7 000b 5701 1908 1024
    0000120: 0454 3a13 1913 c600 1719 1319 0810 2504
    0000130: 54b8 003a 1908 1026 0454 a700 0a01 1908
    0000140: 1027 0454 003a 1403 360c 0336 0d19 0810
    0000150: 2804 54bb 0053 59b7 0054 c000 563a 0e19
    0000160: 0e3a 0f03 3610 1908 1029 0454 b200 592b
    0000170: 1607 190f 1914 c000 5bb9 005f 0200 b600
    0000180: 63b2 0068 3a0d 1908 102a 0454 190e b900
    0000190: 6b01 0000 0019 0810 2b04 54b1          
  Stackmap Table:
    append_frame(@22,Object[#1933])
    same_frame(@33)
    same_frame(@50)
    same_frame(@74)
    full_frame(@227,{Object[#2],Object[#31],Object[#139],Object[#141],Object[#143],Object[#145],Integer,Long,Object[#2],Integer,Object[#147],Object[#71],Integer,Integer,Object[#141],Integer,Object[#31]},{})
    same_frame(@249)
    same_locals_1_stack_item_frame(@272,Object[#141])
    full_frame(@282,{Object[#2],Object[#31],Object[#139],Object[#141],Object[#143],Object[#145],Integer,Long,Object[#2],Integer,Object[#147],Object[#71],Integer,Integer},{Object[#141]})
    same_locals_1_stack_item_frame(@290,Object[#141])
    full_frame(@317,{Object[#2],Object[#31],Object[#139],Object[#141],Object[#143],Object[#145],Integer,Long,Object[#2],Integer,Object[#147],Object[#71],Integer,Integer,Top,Top,Top,Object[#141]},{})
    same_locals_1_stack_item_frame(@324,Object[#31])

	at io.realm.kotlin.internal.RealmUtilsKt.copyToRealm(RealmUtils.kt:215)
	at io.realm.kotlin.internal.RealmUtilsKt.copyToRealm$default(RealmUtils.kt:139)
	at io.realm.kotlin.internal.InternalMutableRealm$DefaultImpls.copyToRealm(InternalMutableRealm.kt:57)
	at io.realm.kotlin.internal.SuspendableWriter$WriterRealm.copyToRealm(SuspendableWriter.kt:52)
	at io.realm.kotlin.MutableRealm$DefaultImpls.copyToRealm$default(MutableRealm.kt:88)
	at gr.desquared.kmmsharedmodule.ExpressionRepository$addExpression$1.invoke(ExpressionRepository.kt:23)
	at gr.desquared.kmmsharedmodule.ExpressionRepository$addExpression$1.invoke(ExpressionRepository.kt:22)
	at io.realm.kotlin.internal.SuspendableWriter$write$2.invokeSuspend(SuspendableWriter.kt:110)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by adam1929** [comment]
Hi @ptsiogas I'm facing same issue. Problem here is, that library-base loads android and JVM jar into classpath; and these libraries are sharing 'same' classes. But classes are not 'same' technically :-) This is meaning of `java.lang.VerifyError` in stacktrace.
I think that solution is to update your `sourceCompatibility` to java 11, but I'm still in investigation. I'm using kotlin android extensions that are deprecated for JDK 11 and I'm lazy now to rewrite whole application to use viewBinding :-D
Good luck

**Comment by adam1929** [comment]
Nothing helped :-/ java11, kotlin 1.8.21, any potential fix for `java.lang.VerifyError` :-/
Only solution was to create Android instrumental test rather than JVM unit test with Robolectric :-/

**Comment by nhachicha** [comment]
Hi @adam1929 @ptsiogas  is this still an issue with the latest release?

**Comment by ptsiogas** [comment]
> Hi @adam1929 @ptsiogas is this still an issue with the latest release?

We have planned to update to the latest version next week. I can provide feedback by the EOW.

**Comment by clementetb** [comment]
@ptsiogas Do you have any update?

**Comment by ChristosSavlidis** [comment]
> @ptsiogas Do you have any update?

Hi @clementetbt today i tried the `1.13.0` and `1.12.0` and I got the same stacktrace as @ptsiogas pinned.

**Comment by KevinBassaDevelopment** [comment]
Any update on this one?

I have the same issue when combining realm&robolectric with jacoco.

Realm tests basically work, but are excluded by code coverage.
Robolectric tests can be included with these settings:
```
  configure<JacocoTaskExtension> {
       isIncludeNoLocationClasses = true
       excludes = listOf("jdk.internal.*")
  }
```

But this then results in tests that contain REALM to fail:

```
Bad local variable type
Exception Details:
  Location:
    io/realm/kotlin/internal/RealmObjectHelper.setObject$io_realm_kotlin_library$default(Lio/realm/kotlin/internal/RealmObjectHelper;Lio/realm/kotlin/internal/RealmObjectReference;Ljava/lang/String;Lio/realm/kotlin/types/BaseRealmObject;Lio/realm/kotlin/UpdatePolicy;Ljava/util/Map;ILjava/lang/Object;)V @137: aload
  Reason:
    Type long_2nd (current frame, locals[8]) is not assignable to reference type
  Current Frame:
    bci: @137
    flags: { }
    locals: { 'io/realm/kotlin/internal/RealmObjectHelper', 'io/realm/kotlin/internal/RealmObjectReference', 'java/lang/String', 'io/realm/kotlin/types/BaseRealmObject', 'io/realm/kotlin/UpdatePolicy', 'java/util/Map', integer, long, long_2nd, top, 'io/realm/kotlin/internal/RealmObjectHelper', integer }
    stack: { }
  Bytecode:
    0000000: b808 0d3a 0815 0610 087e 9a00 0c19 0810
    0000010: 1404 54a7 000e b200 983a 0419 0810 1504
    0000020: 5415 0610 107e 9a00 0c19 0810 1604 54a7
    0000030: 001b 1908 1017 0454 bb00 9a59 b700 9bc0
    0000040: 0091 3a05 1908 1018 0454 2b12 11b8 0017
    0000050: 2c12 19b8 0017 1904 121b b800 1719 0512
    0000060: 1db8 0017 0336 0619 0810 1904 542b b600
    0000070: 2219 0810 1a04 542b 2cb6 0026 b900 2c01
    0000080: 0037 072a 3a0a 0336 0b19 0810 1b04 542b
    0000090: b600 2219 0810 1c04 542b b600 303a 0c2b
    00000a0: b600 343a 0d03 360e 0336 0f2d 59c6 006d
    00000b0: 3a10 0336 1119 0810 1d04 542d b800 3a3a
    00000c0: 1219 12c6 0036 1908 101e 0454 1912 b600
    00000d0: 3419 0db8 003e 9900 0d2d 1908 101f 0454
    00000e0: a700 30bb 0040 5912 4219 0810 2004 54b7
    00000f0: 0045 1908 1021 0454 bf19 0c19 0db9 004b
    0000100: 0100 2d19 0419 05b8 0051 1908 1022 0454
    0000110: 0019 0810 2304 54a7 000b 5701 1908 1024
    0000120: 0454 3a13 1913 c600 1719 1319 0810 2504
    0000130: 54b8 003a 1908 1026 0454 a700 0a01 1908
    0000140: 1027 0454 003a 1403 360c 0336 0d19 0810
    0000150: 2804 54bb 0053 59b7 0054 c000 563a 0e19
    0000160: 0e3a 0f03 3610 1908 1029 0454 b200 592b
    0000170: 1607 190f 1914 c000 5bb9 005f 0200 b600
    0000180: 63b2 0068 3a0d 1908 102a 0454 190e b900
    0000190: 6b01 0000 0019 0810 2b04 54b1          
  Stackmap Table:
    append_frame(@22,Object[#2063])
    same_frame(@33)
    same_frame(@50)
    same_frame(@74)
    full_frame(@227,{Object[#2],Object[#31],Object[#139],Object[#141],Object[#143],Object[#145],Integer,Long,Object[#2],Integer,Object[#147],Object[#71],Integer,Integer,Object[#141],Integer,Object[#31]},{})
    same_frame(@249)
    same_locals_1_stack_item_frame(@272,Object[#141])
    full_frame(@282,{Object[#2],Object[#31],Object[#139],Object[#141],Object[#143],Object[#145],Integer,Long,Object[#2],Integer,Object[#147],Object[#71],Integer,Integer},{Object[#141]})
    same_locals_1_stack_item_frame(@290,Object[#141])
    full_frame(@317,{Object[#2],Object[#31],Object[#139],Object[#141],Object[#143],Object[#145],Integer,Long,Object[#2],Integer,Object[#147],Object[#71],Integer,Integer,Top,Top,Top,Object[#141]},{})
    same_locals_1_stack_item_frame(@324,Object[#31])
```
