### ISSUE TITLE
Orphaned embedded objects are not deleted when migrating from Object to Embedded Object

### ISSUE THREAD

**Issue by sipersso** [realm/realm-kotlin#1464]
### How frequently does the bug occur?

-- select --

### Description

According this ticket migration from object to embedded should now be automatic in core and orphaned children should automatically be deleted: https://github.com/realm/realm-core/pull/5737

This doesn't seem to work in the Kotlin SDK. I have a unit test where I have an orphaned object and do an upgrade. Instead of deleting the orphaned object, the migration fails and the app crashes. I have no such issues on iOS

### Stacktrace & log output

```shell
java.lang.IllegalStateException: [RLM_ERR_ILLEGAL_OPERATION]: Cannot convert 'MyEmbeddedObject:' to embedded: at least one object has no incoming links and would be deleted.
at io.realm.kotlin.internal.interop.CoreErrorConverter.asThrowable(CoreErrorConverter.kt:44)
at io.realm.kotlin.internal.interop.realmcJNI.open_realm_with_scheduler(Native Method)
at io.realm.kotlin.internal.interop.realmc.open_realm_with_scheduler(realmc.java:1757)
at io.realm.kotlin.internal.interop.RealmInterop.realm_open(RealmInterop.kt:194)
at io.realm.kotlin.internal.interop.RealmInterop.realm_open$default(RealmInterop.kt:183)
at io.realm.kotlin.internal.ConfigurationImpl.openRealm$suspendImpl(ConfigurationImpl.kt:110)
at io.realm.kotlin.internal.ConfigurationImpl.openRealm(Unknown Source:0)
at io.realm.kotlin.internal.RealmImpl$1.invokeSuspend(RealmImpl.kt:125)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
at io.realm.kotlin.internal.platform.CoroutineUtilsSharedJvmKt.runBlocking(CoroutineUtilsSharedJvm.kt:22)
at io.realm.kotlin.internal.platform.CoroutineUtilsSharedJvmKt.runBlocking$default(CoroutineUtilsSharedJvm.kt:21)
at io.realm.kotlin.internal.RealmImpl.<init>(RealmImpl.kt:107)
at io.realm.kotlin.internal.RealmImpl.<init>(Unknown Source:0)
at io.realm.kotlin.internal.RealmImpl$Companion.create$io_realm_kotlin_library(RealmImpl.kt:285)
at io.realm.kotlin.Realm$Companion.open(Realm.kt:82)
```

### Can you reproduce the bug?

Always

### Version

1.10.1

### What Atlas App Services are you using?

-- select --

### Are you using encryption?

-- select --

### Platform OS and version(s)

Android

### Build environment

Android Studio version: ...
Android Build Tools version: ...
Gradle version: ...

**Comment by sipersso** [comment]
I assume that this is exactly the same issue that used to be in the Java SDK: https://github.com/realm/realm-java/issues/7769 and was fixed by https://github.com/realm/realm-java/pull/7772

**Comment by rorbech** [comment]
Hi @sipersso. Thanks for the report. It is a bit different in Kotlin as we do not yet support manual migration and can handle this on a per class basis. Only option in Kotlin is to set the default behavior on the configuration. We will see to expose that option on the configuration.

**Comment by sipersso** [comment]
I don't understand. I did supply a migration block and was able to do the same workaround as I was previously using in java before it was handled automatically. What default behavior on the configuration are you talking about?

**Comment by sipersso** [comment]
FIY: Same goes for when an object has multiple incoming links. This doesn't work either, but I guess it is the same issue?  Any updates on when this would be fixed?

**Comment by sipersso** [comment]
@rorbech any info on when this might be released? I am currently blocked from releasing a big feature because of this. Would be nice to get a feel for how long it might take so I can adjust priorities.

**Comment by sipersso** [comment]
I noticed that https://github.com/realm/realm-kotlin/pull/1490 is now merged. Any updates on the release? I can use the snapshot build for beta testing, but hesitate to use snapshots in production.
