### ISSUE TITLE
Updating RealmList using apply block

### ISSUE THREAD

**Issue by justinrxu** [realm/realm-kotlin#1484]
### How frequently does the bug occur?

Always

### Description

I have a managed `RealmList` that I want to make editable in the scope of a write transaction, that is mutable as follows:

RealmSettleAction.kt

```
internal class RealmSettleAction : SettleAction(), RealmObject {

   ...

    @Ignore
    override val transactionRecords: MutableList<TransactionRecord> =
        object : AbstractMutableList<TransactionRecord>() {
            override fun get(index: Int): TransactionRecord = _transactionRecords[index]

            override fun add(index: Int, element: TransactionRecord) = {
                println("adding new transactionRecord")
                _transactionRecords.add(index, element.toRealmTransactionRecord())
            }

            override fun removeAt(index: Int): TransactionRecord = 
                _transactionRecords.removeAt(index)

            override fun set(index: Int, element: TransactionRecord): TransactionRecord = 
                _transactionRecords.set(index, element.toRealmTransactionRecord())

            override val size: Int
                get() = _transactionRecords.size
        }

    ...

    @PersistedName("transactionRecords")
    var _transactionRecords: RealmList<RealmTransactionRecord> = realmListOf()

    ...

}
```
where `_transactionRecords` is the underlying `RealmList` and `transactionRecords` acts like a wrapper object between `MutableList<TransactionRecord>` and `RealmList<RealmTransactionRecord>`, where `RealmTransactionRecord` is an `EmbeddedRealmObjec` that is a subclass to a general object model `TransactionRecord`.

I also have an update function

RealmSettleActionRepository.kt

```
override suspend fun updateSettleAction(
    settleAction: SettleAction,
    block: SettleAction.() -> Unit
): RealmSettleAction? {
    return realm.write {
        println("starting write transaction")
        copyToRealm(
            (settleAction as RealmSettleAction).apply(block),
            UpdatePolicy.ALL
        ).also {
           println("write transaction over")
        }
    }
}
```
That I use to add/change transactionRecords like so:

SettleActionService.kt

`updateSettleAction(settleAction) { transactionRecords.add(newTransactionRecord) }`

However, this causes a `java.lang.IllegalStateException: [RLM_ERR_WRONG_TRANSACTION_STATE]: Cannot modify managed List outside of a write transaction.`, and I can't figure out why, since the modify block is technically executed inside a `realm.write`.

I also have 3 print statements throughout the flow: one statement when the write transaction starts, one inside `transactionRecords.add`, right before _transactionRecords.add is called, and one right after the apply block is called on the `RealmSettleAction`. Only the first two statements print, followed by the thrown error, which I assume means that `transactionRecords.add` is called inside the write transaction, and then the error is thrown before the write ends. Is this just an intended behavior? Or am I missing something here

### Stacktrace & log output

```shell
java.lang.IllegalStateException: [RLM_ERR_WRONG_TRANSACTION_STATE]: Cannot modify managed List outside of a write transaction.
    at io.realm.kotlin.internal.interop.CoreErrorConverter.asThrowable(CoreErrorConverter.kt:44)
    at io.realm.kotlin.internal.interop.realmcJNI.realm_list_insert_embedded(Native Method)
    at io.realm.kotlin.internal.interop.realmc.realm_list_insert_embedded(realmc.java:726)
    at io.realm.kotlin.internal.interop.RealmInterop.realm_list_insert_embedded(RealmInterop.kt:523)
    at io.realm.kotlin.internal.EmbeddedRealmObjectListOperator.insert(RealmListInternal.kt:405)
    at io.realm.kotlin.internal.EmbeddedRealmObjectListOperator.insert(RealmListInternal.kt:389)
    at io.realm.kotlin.internal.ListOperator$DefaultImpls.insert$default(RealmListInternal.kt:211)
    at io.realm.kotlin.internal.ManagedRealmList.add(RealmListInternal.kt:87)
    at com.grup.models.realm.RealmSettleAction$transactionRecords$1.add(RealmSettleAction.kt:31)
    at com.grup.models.realm.RealmSettleAction$transactionRecords$1.add(RealmSettleAction.kt:27)
    at java.util.AbstractList.add(AbstractList.java:111)
    at com.grup.service.SettleActionService$createSettleActionTransaction$2.invoke(SettleActionService.kt:35)
    at com.grup.service.SettleActionService$createSettleActionTransaction$2.invoke(SettleActionService.kt:34)
    at com.grup.repositories.abstract.RealmSettleActionRepository$updateSettleAction$2.invoke(RealmSettleActionRepository.kt:39)
    at com.grup.repositories.abstract.RealmSettleActionRepository$updateSettleAction$2.invoke(RealmSettleActionRepository.kt:37)
    at io.realm.kotlin.internal.SuspendableWriter$write$2.invokeSuspend(SuspendableWriter.kt:110)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
```
```


### Can you reproduce the bug?

Always

### Reproduction Steps

Included in description

### Version

1.10.2

### What Atlas App Services are you using?

Atlas Device Sync

### Are you using encryption?

No

### Platform OS and version(s)

Android 13.0

### Build environment

Android Studio version: Android Studio Giraffe 2022.3.1
Android Build Tools version: 34
Gradle version: 8.1.0

**Comment by cmelchior** [comment]
Hi @justinrxu The root cause for this is described here: https://github.com/realm/realm-kotlin/issues/1484, so I will fold the issue into that one. 

But the reason you are getting the error is that you cannot edit objects passed into the write. You must use `findLatest(obj)` on them before you can edit them. The reason is that Realm has ACID guarantees, so we need to forward the database to the latest "version" before you can make any edits, and when you do that, the object might no longer exist.
