### ISSUE TITLE
Migration to AGP, gradle 8.0 and above 

### ISSUE THREAD

**Issue by AsifAliJohari** [realm/realm-kotlin#1486]
on Upgrade gradle version and using android studio grife, realm dependncy not resolve, there is some compitabilaty issue. Please guide . how to fixed it. i already upgrade project gradle. is there any beta version or aolution like for realm java sdk

**Comment by AsifAliJohari** [comment]
on Upgrade gradle version and using android studio grife, realm dependncy not resolve, there is some compitabilaty issue. Please guide . how to fixed it. i already upgrade project gradle. is there any beta version or solution like for realm java sdk

**Comment by florinleu** [comment]
Hi @cmelchior . We also bumped into some issues after upgrading to the latest Android Studio and gradle 8.3. This is the error we get when compiling:
```
Details: Internal error in file lowering: java.lang.AssertionError: Function 'setMutableInt' not found in class 'RealmObjectHelper'
	at io.realm.kotlin.compiler.IrUtilsKt.lookupFunction(IrUtils.kt:194)
	at io.realm.kotlin.compiler.IrUtilsKt.lookupFunction$default(IrUtils.kt:192)
	at io.realm.kotlin.compiler.AccessorModifierIrGeneration.<init>(AccessorModifierIrGeneration.kt:139)
	at io.realm.kotlin.compiler.RealmModelLowering.lower(RealmModelLoweringExtension.kt:96)
	at org.jetbrains.kotlin.backend.common.ClassLoweringVisitor.visitClass(Lower.kt:101)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitClass(IrElementVisitorVoid.kt:111)
	at org.jetbrains.kotlin.backend.common.ClassLoweringVisitor.visitClass(Lower.kt:92)
	at org.jetbrains.kotlin.backend.common.ClassLoweringVisitor.visitClass(Lower.kt:92)
	at org.jetbrains.kotlin.ir.declarations.IrClass.accept(IrClass.kt:64)
	at org.jetbrains.kotlin.ir.declarations.IrFile.acceptChildren(IrFile.kt:36)
	at org.jetbrains.kotlin.ir.visitors.IrVisitorsKt.acceptChildrenVoid(IrVisitors.kt:15)
	at org.jetbrains.kotlin.backend.common.ClassLoweringVisitor.visitElement(Lower.kt:96)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitPackageFragment(IrElementVisitorVoid.kt:190)
	at org.jetbrains.kotlin.backend.common.ClassLoweringVisitor.visitPackageFragment(Lower.kt:92)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitFile(IrElementVisitorVoid.kt:200)
	at org.jetbrains.kotlin.backend.common.ClassLoweringVisitor.visitFile(Lower.kt:92)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitFile(IrElementVisitorVoid.kt:198)
	at org.jetbrains.kotlin.backend.common.ClassLoweringVisitor.visitFile(Lower.kt:92)
	at org.jetbrains.kotlin.backend.common.ClassLoweringVisitor.visitFile(Lower.kt:92)
	at org.jetbrains.kotlin.ir.declarations.IrFile.accept(IrFile.kt:30)
	at org.jetbrains.kotlin.ir.visitors.IrVisitorsKt.acceptVoid(IrVisitors.kt:11)
	at org.jetbrains.kotlin.backend.common.LowerKt.runOnFilePostfix(Lower.kt:89)
	at io.realm.kotlin.compiler.RealmModelLowering.lower(RealmModelLoweringExtension.kt:56)
	at org.jetbrains.kotlin.backend.common.LowerKt.lower(Lower.kt:75)
	at io.realm.kotlin.compiler.RealmModelLoweringExtension.generate(RealmModelLoweringExtension.kt:45)
	at org.jetbrains.kotlin.backend.jvm.JvmIrCodegenFactory.convertToIr$lambda$1(JvmIrCodegenFactory.kt:186)
	at org.jetbrains.kotlin.psi2ir.Psi2IrTranslator.generateModuleFragment(Psi2IrTranslator.kt:104)
	at org.jetbrains.kotlin.backend.jvm.JvmIrCodegenFactory.convertToIr(JvmIrCodegenFactory.kt:218)
	at org.jetbrains.kotlin.backend.jvm.JvmIrCodegenFactory.convertToIr(JvmIrCodegenFactory.kt:55)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.convertToIr(KotlinToJVMBytecodeCompiler.kt:225)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:102)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:47)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:167)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:53)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:101)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:47)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
	at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:485)
	at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:131)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.doCompile(IncrementalCompilerRunner.kt:424)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileImpl(IncrementalCompilerRunner.kt:360)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileNonIncrementally(IncrementalCompilerRunner.kt:242)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:98)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.execIncrementalCompiler(CompileServiceImpl.kt:625)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.access$execIncrementalCompiler(CompileServiceImpl.kt:101)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1746)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(Unknown Source)
	at java.rmi/sun.rmi.transport.Transport$1.run(Unknown Source)
	at java.rmi/sun.rmi.transport.Transport$1.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Unknown Source)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(Unknown Source)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(Unknown Source)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.AssertionError: Function 'setMutableInt' not found in class 'RealmObjectHelper'
```

**Comment by cmelchior** [comment]
@florinleu That looks like an incremental compilation error. Does it also happens if you do a clean build?

**Comment by AsifAliJohari** [comment]
Hi @cmelchior ,thanks for responce. sorry for late reply. 
I am using  realm kotlin sdk leatest version. 
for android project with multi module 
with gradle 8.0 
![IMG_20230824_102705_118.jpg](https://github.com/realm/realm-kotlin/assets/27045955/75f15485-1bac-497d-885e-b36062881b18)

i found issue related to this problem  in java sdk .i already mention above

**Comment by AsifAliJohari** [comment]
> Hi @AsifAliJohari I tried to upgrade our Intro sample project to AGP 8 and Gradle 8. It seems to work fine if you adjust for a ew things. You can see it here: https://github.com/realm/realm-kotlin-samples/pull/43
> 
> What exactly are the issue you are running into?

i check it ,al step already follow. 
I found that AGP remove transform library

**Comment by AsifAliJohari** [comment]
> Hi @cmelchior ,thanks for responce. sorry for late reply. 
> I am using  realm kotlin sdk leatest version. 
> for android project with multi module 
> with gradle 8.0 
> ![IMG_20230824_102705_118.jpg](https://github.com/realm/realm-kotlin/assets/27045955/75f15485-1bac-497d-885e-b36062881b18)
> 
> i found issue related to this problem  in java sdk .i already mention above 
> 

Gradle with kotlin DSL and buildSrc

**Comment by AsifAliJohari** [comment]
![IMG_20230824_124254_017.jpg](https://github.com/realm/realm-kotlin/assets/27045955/1bc68006-b24b-469a-8e45-e648d9bd410b)

it may help you understand problem

**Comment by AsifAliJohari** [comment]
![IMG_20230824_124254_017.jpg](https://github.com/realm/realm-kotlin/assets/27045955/1bc68006-b24b-469a-8e45-e648d9bd410b)

@cmelchior  may help you understand problem


in java sdk
![IMG_20230824_125130_832.jpg](https://github.com/realm/realm-kotlin/assets/27045955/2f36a90e-60db-4fdd-8947-d08c27433b7f)

**Comment by florinleu** [comment]
@cmelchior do you have any updates on this? We're still forced to use realm 1.5.2 even if the latest release is 1.10.2.
