### ISSUE TITLE
[GHA] Flaky test [android-emulator]: ProgressListenerTests.completesOnClose

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-kotlin#1628]
Saw this on Github actions: https://github.com/realm/realm-kotlin/runs/20418206939

```
java.lang.IllegalStateException: Cannot perform this operation on an invalid/deleted reference.
at io.realm.kotlin.internal.interop.NativePointerKt.<clinit>(NativePointer.kt:19)
at io.realm.kotlin.internal.interop.NativePointerKt.use(Unknown Source:0)
at io.realm.kotlin.internal.ConfigurationImpl.openRealm$suspendImpl(ConfigurationImpl.kt:114)
at io.realm.kotlin.internal.ConfigurationImpl.openRealm(Unknown Source:0)
at io.realm.kotlin.mongodb.internal.SyncConfigurationImpl.openRealm(SyncConfigurationImpl.kt:138)
at io.realm.kotlin.internal.RealmImpl$1.invokeSuspend(RealmImpl.kt:133)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
at io.realm.kotlin.internal.platform.CoroutineUtilsSharedJvmKt.runBlocking(CoroutineUtilsSharedJvm.kt:22)
at io.realm.kotlin.internal.platform.CoroutineUtilsSharedJvmKt.runBlocking$default(CoroutineUtilsSharedJvm.kt:21)
at io.realm.kotlin.internal.RealmImpl.<init>(RealmImpl.kt:115)
at io.realm.kotlin.internal.RealmImpl.<init>(Unknown Source:0)
at io.realm.kotlin.internal.RealmImpl$Companion.create$io_realm_kotlin_library(RealmImpl.kt:318)
at io.realm.kotlin.Realm$Companion.open(Realm.kt:83)
at io.realm.kotlin.test.mongodb.common.AppTests.encryptedMetadataRealm_openWithoutKeyThrows(AppTests.kt:466)
```

**Comment by cmelchior** [comment]
Also failed here: https://github.com/realm/realm-kotlin/runs/20431309864 (on Android Emulator)

**Comment by cmelchior** [comment]
Fixed by https://github.com/realm/realm-kotlin/pull/1645
