### ISSUE TITLE
`NullPointerException` while waiting for the synchronization of a subscription.

### ISSUE THREAD

**Issue by clementetb** [realm/realm-kotlin#1671]
### How frequently does the bug occur?

Always

### Description

While waiting for the synchronization of a subscription set a null pointer is thrown.

### Stacktrace & log output

```shell
Fatal Exception: java.lang.NullPointerException:
       at io.realm.kotlin.mongodb.internal.SubscriptionSetImpl.waitForSynchronization-VtjQ1oo(SubscriptionSetImpl.java:215)
       at io.realm.kotlin.mongodb.internal.SubscriptionSetImpl$waitForSynchronization$1.invokeSuspend(SubscriptionSetImpl.java:13)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:13)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:111)
       at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.java:34)
       at kotlinx.coroutines.scheduling.TaskImpl.run(TaskImpl.java:2)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java:93)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.java:93)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.java:93)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.java:93)
```

### Can you reproduce the bug?

Always

### Version

1.13.0

### What Atlas App Services are you using?

Atlas Device Sync

### Are you using encryption?

No

### Platform OS and version(s)

-

**Comment by clementetb** [comment]
The cause is a missing state `AwaitingMark` at the `CoreSubscriptionSetState`.
