### ISSUE TITLE
[RLM_ERR_UNSUPPORTED_FILE_FORMAT_VERSION]: Database has an unsupported version (9) and cannot be upgraded

### ISSUE THREAD

**Issue by fngbala-luna** [realm/realm-kotlin#1808]
### How frequently does the bug occur?

Sometimes

### Description

Hi,
Some of our users are experiencing a crash when trying to run our app. 

As I understand it, it's because the realm file use an unsuported version (number 9 according to the stack trace). 

I think I have the crash starting from the Realm kotlin SDK version **1.16.0**. 
The first version of the SDK used in the project is **1.11.1**. 

Anyone knows what might cause this crash and how to fix it ? 

One of our theory is that the user are updating the app from a "too old" version of realm, What is strange is that the older version is only 1.11.1 (that, according to the release note  "_Generates Realms with file format v23_")

Thanks in advance.  

PS : I tried to reproduce it, but never I never managed to make the app crash ... But a "lot" of our users are crashing. 

### Stacktrace & log output

```shell
Fatal Exception: java.lang.RuntimeException
Unable to create application "My_package": java.lang.IllegalStateException: [RLM_ERR_UNSUPPORTED_FILE_FORMAT_VERSION]: Database has an unsupported version (9) and cannot be upgraded


Caused by java.lang.IllegalStateException: [RLM_ERR_UNSUPPORTED_FILE_FORMAT_VERSION]: Database has an unsupported version (9) and cannot be upgraded
       at io.realm.kotlin.internal.interop.CoreErrorConverter.asThrowable(CoreErrorConverter.kt:47)
       at io.realm.kotlin.internal.interop.realmcJNI.realm_open(realmcJNI.java)
       at io.realm.kotlin.internal.interop.realmc.realm_open(realmc.java:434)
       at io.realm.kotlin.internal.interop.RealmInterop.realm_open(RealmInterop.kt:237)
       at io.realm.kotlin.internal.ConfigurationImpl.openRealm$lambda$0(ConfigurationImpl.java:109)
       at io.realm.kotlin.internal.interop.NativePointerKt.use(NativePointer.kt:53)
       at io.realm.kotlin.internal.ConfigurationImpl.openRealm$suspendImpl(ConfigurationImpl.java:108)
       at io.realm.kotlin.internal.ConfigurationImpl.openRealm(ConfigurationImpl.java:100)
       at io.realm.kotlin.internal.RealmImpl$1.invokeSuspend(RealmImpl.kt:133)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
       at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277)
       at kotlinx.coroutines.BlockingCoroutine.joinBlocking(BlockingCoroutine.java:95)
       at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(BuildersKt__Builders.kt:69)
       at kotlinx.coroutines.BuildersKt.runBlocking(Builders.kt:1)
       at io.realm.kotlin.internal.platform.CoroutineUtilsSharedJvmKt.runBlocking(CoroutineUtilsSharedJvm.kt:22)
       at io.realm.kotlin.internal.platform.CoroutineUtilsSharedJvmKt.runBlocking$default(CoroutineUtilsSharedJvm.kt:21)
       at io.realm.kotlin.internal.RealmImpl.<init>(RealmImpl.kt:115)
       at io.realm.kotlin.internal.RealmImpl.<init>(RealmImpl.kt:133)
       at io.realm.kotlin.internal.RealmImpl$Companion.create$io_realm_kotlin_library(RealmImpl.kt:318)
       at io.realm.kotlin.Realm$Companion.open(Realm.java:83)
```

### Can you reproduce the bug?

No

### Version

1.16.0

### What Atlas App Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

Android (Min SDK 26)

### Build environment

Android Studio version: ...
Android Build Tools version: ...
Gradle version: ...

**Comment by fngbala-luna** [comment]
Hi 👋
Can someone help me here ?

**Comment by rorbech** [comment]
Hi @fngbala-luna. Seems like you might have been hit by https://github.com/realm/realm-core/issues/7747. We are working on a release that includes a fix for that. Can you confirm that you are in fact compating the realm files?

**Comment by fngbala-luna** [comment]
Hi, thanks for your answer.

Not sure I am compating the realm files. Unless it's done by default ?

**Comment by fngbala-luna** [comment]
Hi,
Any news on the issue ?
