### ISSUE TITLE
StackOverflowError during compilation after updating both kotlin and realm-kotlin to 2.0.0

### ISSUE THREAD

**Issue by TwoEightNine** [realm/realm-kotlin#1847]
### How frequently does the bug occur?

Always

### Description

hello! i'm trying to update my project to kotlin 2.0 and therefore have to update my realm-kotlin version. but at the compilation step i always receive `StackOverflowError`. (full stacktrace: https://pastebin.com/raw/fHyjEmZK.)

i tried different versions (2.0.0, 2.1.0, 2.2.0, 2.3.0) with correspondent kotlin versions, it doesn't help.

since i see realm plugin there in stacktrace, i decided to create the issue.

### Stacktrace & log output

```shell
e: java.lang.StackOverflowError
        <omitted since repeated>
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.jetbrains.kotlin.fir.java.declarations.FirJavaClass.getSuperTypeRefs(FirJavaClass.kt:72)
	at io.realm.kotlin.compiler.IrUtilsKt.isBaseRealmObject(IrUtils.kt:211)
	at io.realm.kotlin.compiler.fir.model.CompanionExtension.getNestedClassifiersNames(CompanionExtension.kt:45)
	at org.jetbrains.kotlin.fir.scopes.impl.FirGeneratedMemberDeclarationsStorage.getClassifierStorage$providers(FirGeneratedScopes.kt:155)
	at org.jetbrains.kotlin.fir.scopes.impl.FirGeneratedClassNestedClassifierScope$Companion.create(FirGeneratedScopes.kt:116)
	at org.jetbrains.kotlin.fir.scopes.impl.FirDeclaredMemberScopeProvider.createNestedClassifierScope(FirDeclaredMemberScopeProvider.kt:120)
	at org.jetbrains.kotlin.fir.scopes.impl.FirDeclaredMemberScopeProvider.access$createNestedClassifierScope(FirDeclaredMemberScopeProvider.kt:26)
	at org.jetbrains.kotlin.fir.scopes.impl.FirDeclaredMemberScopeProvider$nestedClassifierCache$1.invoke(FirDeclaredMemberScopeProvider.kt:39)
	at org.jetbrains.kotlin.fir.scopes.impl.FirDeclaredMemberScopeProvider$nestedClassifierCache$1.invoke(FirDeclaredMemberScopeProvider.kt:39)
	at org.jetbrains.kotlin.fir.caches.FirThreadUnsafeCache.getValue(FirThreadUnsafeCachesFactory.kt:40)
	at org.jetbrains.kotlin.fir.scopes.impl.FirDeclaredMemberScopeProvider.nestedClassifierScope(FirDeclaredMemberScopeProvider.kt:182)
	at org.jetbrains.kotlin.fir.scopes.impl.FirDeclaredMemberScopeProviderKt.nestedClassifierScope(FirDeclaredMemberScopeProvider.kt:167)
	at org.jetbrains.kotlin.fir.extensions.FirExtensionDeclarationsSymbolProvider.generateClassLikeDeclaration(FirExtensionDeclarationsSymbolProvider.kt:106)
	at org.jetbrains.kotlin.fir.extensions.FirExtensionDeclarationsSymbolProvider.access$generateClassLikeDeclaration(FirExtensionDeclarationsSymbolProvider.kt:27)
	at org.jetbrains.kotlin.fir.extensions.FirExtensionDeclarationsSymbolProvider$classCache$1.invoke(FirExtensionDeclarationsSymbolProvider.kt:44)
	at org.jetbrains.kotlin.fir.extensions.FirExtensionDeclarationsSymbolProvider$classCache$1.invoke(FirExtensionDeclarationsSymbolProvider.kt:43)
	at org.jetbrains.kotlin.fir.caches.FirThreadUnsafeCache.getValue(FirThreadUnsafeCachesFactory.kt:40)
	at org.jetbrains.kotlin.fir.extensions.FirExtensionDeclarationsSymbolProvider.getClassLikeSymbolByClassId(FirExtensionDeclarationsSymbolProvider.kt:246)
	at org.jetbrains.kotlin.fir.extensions.FirSwitchableExtensionDeclarationsSymbolProvider.getClassLikeSymbolByClassId(FirSwitchableExtensionDeclarationsSymbolProvider.kt:62)
	at org.jetbrains.kotlin.fir.resolve.providers.impl.FirCachingCompositeSymbolProvider.computeClass(FirCachingCompositeSymbolProvider.kt:147)
	at org.jetbrains.kotlin.fir.resolve.providers.impl.FirCachingCompositeSymbolProvider.access$computeClass(FirCachingCompositeSymbolProvider.kt:27)
	at org.jetbrains.kotlin.fir.resolve.providers.impl.FirCachingCompositeSymbolProvider$special$$inlined$createCache$1.invoke(FirCachesFactory.kt:71)
	at org.jetbrains.kotlin.fir.resolve.providers.impl.FirCachingCompositeSymbolProvider$special$$inlined$createCache$1.invoke(FirCachesFactory.kt:69)
	at org.jetbrains.kotlin.fir.caches.FirThreadUnsafeCache.getValue(FirThreadUnsafeCachesFactory.kt:40)
	at org.jetbrains.kotlin.fir.resolve.providers.impl.FirCachingCompositeSymbolProvider.getClassLikeSymbolByClassId(FirCachingCompositeSymbolProvider.kt:174)
	at org.jetbrains.kotlin.fir.resolve.LookupTagUtilsKt.toSymbol(LookupTagUtils.kt:59)
	at org.jetbrains.kotlin.fir.types.ConeTypeContext.toClassLikeSymbol(ConeTypeContext.kt:286)
	at org.jetbrains.kotlin.fir.types.ConeTypeContext.getParameters(ConeTypeContext.kt:278)
	at org.jetbrains.kotlin.load.java.typeEnhancement.AbstractSignatureParts.toIndexed$lambda$23$lambda$22(AbstractSignatureParts.kt:215)
	at org.jetbrains.kotlin.load.java.typeEnhancement.AbstractSignatureParts.flattenTree(AbstractSignatureParts.kt:201)
	at org.jetbrains.kotlin.load.java.typeEnhancement.AbstractSignatureParts.flattenTree(AbstractSignatureParts.kt:201)
	at org.jetbrains.kotlin.load.java.typeEnhancement.AbstractSignatureParts.flattenTree(AbstractSignatureParts.kt:205)
	at org.jetbrains.kotlin.load.java.typeEnhancement.AbstractSignatureParts.toIndexed(AbstractSignatureParts.kt:211)
	at org.jetbrains.kotlin.load.java.typeEnhancement.AbstractSignatureParts.computeIndexedQualifiers(AbstractSignatureParts.kt:174)
	at org.jetbrains.kotlin.load.java.typeEnhancement.AbstractSignatureParts.computeIndexedQualifiers$default(AbstractSignatureParts.kt:169)
	at org.jetbrains.kotlin.fir.java.enhancement.FirSignatureEnhancement.enhance(SignatureEnhancement.kt:834)
	at org.jetbrains.kotlin.fir.java.enhancement.FirSignatureEnhancement.enhance$default(SignatureEnhancement.kt:828)
	at org.jetbrains.kotlin.fir.java.enhancement.FirSignatureEnhancement.enhanceSuperType(SignatureEnhancement.kt:636)
	at org.jetbrains.kotlin.fir.java.enhancement.FirSignatureEnhancement.enhanceSuperTypes(SignatureEnhancement.kt:591)
	at org.jetbrains.kotlin.fir.java.declarations.FirJavaClass.superTypeRefs_delegate$lambda$1(FirJavaClass.kt:74)
```

### Can you reproduce the bug?

Always

### Reproduction Steps

1. update kotlin up to 2.0.*
2. update realm-kotlin up to 2.*.0 (correspondingly to the kotlin version)
3. sync project
4. build the app

### Version

2.0.0+

### What Atlas App Services are you using?

Local Database only

### Are you using encryption?

Yes

### Platform OS and version(s)

I wasn't able to even launch

### Build environment

Android Studio version: 2024.2.1 Patch 1
Android Build Tools version: not specified
Gradle version: 8.10.2 (AGP 8.7.0)

**Comment by DmytroSkopiuk** [comment]
Same error with Protobuf dependency (all versions). Without Protobuf works fine in Kotlin2.

**Comment by tinoue** [comment]
The same error occurs with Kotlin 2.0, Realm 2.3, and protobuf-kotlin-lite 4.29.2.
I hope that supporting for Kotlin 2.1.0 will fix the issue, as it seems to be caused by Kotlin.

**Comment by Crzy633** [comment]
+1

**Comment by Neoxsam** [comment]
+1

**Comment by mefetran** [comment]
+1. Can't use with protobuf

**Comment by tinoue** [comment]
I’m migrating from Realm-Kotlin to [krdb](https://github.com/XilinJia/krdb), which is a fork of it.
krdb supports Kotlin 2.1.20, but the StackOverflowError still occurs.

I’ve made a fix for this issue in my private repository: https://github.com/tinoue/krdb/tree/fix-stackoverflow.

**Comment by LouisCAD** [comment]
Do you get the StackOverflow issue with our Maven Central published fork used with Kotlin 2.2.0?

https://github.com/Infomaniak/realm-kotlin/releases/tag/3.2.8-2

**Comment by tinoue** [comment]
@LouisCAD Thanks for your notification. I tried 3.2.8-2 and 3.2.9 with Kotlin2.2.10 and protobuf4.32.1, but I still get the StackOverflow (recursive call of io.realm.kotlin.compiler.IrUtilsKt.isBaseRealmObject())

**Comment by adamburleybc** [comment]
We are also blocked by this issue.

@tinoue are you willing to open a PR to this repo with your change? then we can try to push for it to be fixed from our side.

**Comment by tinoue** [comment]
@adamburleybc The following diff can be applied to this repo: https://github.com/tinoue/krdb/commit/e7f5f30339a304ee3d683be16315b02e319bfb6e

**Comment by adamburleybc** [comment]
I have done some investigation on this (including forking Realm and adding lots of logging to the compiler plugin) and I believe I've found a possible workaround (at least for our codebase).

# Cause of the issue

I found that the issue is due to having a class with a parent class with type parameter of a static nested class, and also having a nested interface which is implemented by its caller.

Below is a minimal example in Java code which triggers the issue. This pattern is quite common in our codebase.

```java
public class ExampleFragment extends Fragment implements ExampleAdapter.ExampleListener {
    @Nullable
    @Override
    public View onCreateView(@NonNull LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        final RecyclerView rootView = new RecyclerView(inflater.getContext());
        rootView.setAdapter(new ExampleAdapter());
        return rootView;
    }

    @Override
    public void exampleMethod(String string) {
    }
}

public class ExampleAdapter extends RecyclerView.Adapter<ExampleAdapter.ViewHolder> {
    public ExampleAdapter() {
    }

    @NonNull
    @Override
    public ViewHolder onCreateViewHolder(@NonNull ViewGroup parent, int position) {
        View view = new TextView(parent.getContext());
        return new ViewHolder(view);
    }

    @Override
    public void onBindViewHolder(@NonNull ViewHolder viewHolder, int position) {
    }

    @Override
    public int getItemCount() {
        return 0;
    }

    static class ViewHolder extends RecyclerView.ViewHolder {
        ViewHolder(View itemView) {
            super(itemView);
        }
    }

    public interface ExampleListener {
        void exampleMethod(String string);
    }
}
```

The issue is caused by the fact that `isBaseRealmObject` calls `superTypeRefs`, which for this kind of class will eventually call `getNestedClassifiersNames`, which itself calls `isBaseRealmObject`. The "nested classifier" is related to the nested classes, i.e. `ExampleAdapter extends RecyclerView.Adapter<ExampleAdapter.ViewHolder>`.

In order to trigger the issue, `ExampleFragment` must be reachable from the rest of the code, or it won't even be processed by the compiler plugin. I found that simply adding an import to `ExampleFragment` (even if it's an unused import) from another, Kotlin-based fragment, was sufficient to trigger the issue.

# Possible workaround

For the above case, I found that simply extracting `ViewHolder` into a separate class rather than being a nested class, was enough to remove the infinite recursion and allow the compilation to proceed. It's a bit of a hack, but it's a better solution for us than forking Realm.

After applying this change to 6-7 different instances of this in our codebase, I was able to pass the Realm compiler plugin stage of the compilation. So it's looking promising at this stage.

**Comment by anoopmaddasseri** [comment]
Hi @tinoue @Neoxsam,
I believe this is caused by the Frontend IR compiler pipeline introduced in Kotlin 2.0, which causes `isBaseRealmObject()` to get stuck in an infinite recursive loop during class resolution.

A fix for this has been merged here:
https://github.com/Infomaniak/realm-kotlin/pull/3

<img width="946" height="292" alt="Image" src="https://github.com/user-attachments/assets/36c80371-5252-4494-a46e-b5b0a877bef7" />

and released in version **3.2.9**:
https://github.com/Infomaniak/realm-kotlin/releases

However, we're still seeing the same error on 3.2.9. Is there a known fix that resolves this purely on the library side, without requiring app-side changes?
