### ISSUE TITLE
Better error message when `io.realm.kotlin` plugin is not applied to module containing module classes

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-kotlin#676]
If the user forgets to add the `io.realm.plugin` to the Gradle module containing the model classes, opening the Realm will crash with a rather unhelpful error message:

```
2022-02-11 20:39:01.377 8805-8854/com.mongodb.hellosyncrealm E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-1
    Process: com.mongodb.hellosyncrealm, PID: 8805
    java.lang.IllegalStateException: Couldn't find companion object of class VisitInfo
        at io.realm.internal.platform.RealmObjectKt.realmObjectCompanion(RealmObject.kt:28)
        at io.realm.internal.ConfigurationImpl.<init>(ConfigurationImpl.kt:78)
        at io.realm.mongodb.SyncConfiguration$Builder.build(SyncConfiguration.kt:142)
        at com.mongodb.hellosyncrealm.ui.home.HomeViewModel$updateData$1.invokeSuspend(HomeViewModel.kt:46)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

We should improve the error message for this case. Maybe something like:

```
 java.lang.IllegalStateException: Couldn't find companion object of class VisitInfo. A common cause for this is when the `io.realm.plugin` is not applied to the Gradle module that contains the VisitInfo class.
```

**Comment by nhachicha** [comment]
fixed via https://github.com/realm/realm-kotlin/pull/698
