### ISSUE TITLE
Better error message when class is not part of the schema

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-kotlin#680]
Right now the user is faced with something like:

```
   java.lang.IllegalArgumentException: Cannot find class: 'VisitInfo
        at io.realm.internal.interop.RealmInterop.classInfo(RealmInterop.kt:653)
        at io.realm.internal.interop.RealmInterop.realm_query_parse(RealmInterop.kt:670)
        at io.realm.internal.query.ObjectQuery$parseQuery$1.invoke(ObjectQuery.kt:153)
        at io.realm.internal.query.ObjectQuery$parseQuery$1.invoke(ObjectQuery.kt:152)
        at io.realm.internal.query.ObjectQuery.tryCatchCoreException(ObjectQuery.kt:162)
        at io.realm.internal.query.ObjectQuery.parseQuery(ObjectQuery.kt:152)
        at io.realm.internal.query.ObjectQuery.<init>(ObjectQuery.kt:52)
        at io.realm.internal.BaseRealmImpl.query(BaseRealmImpl.kt:82)
```

Instead, we should be more explicit, perhaps: "Cannot find class 'VisitInfo'. Has the class been added to the schema for the realm?`

**Comment by nhachicha** [comment]
fixed via https://github.com/realm/realm-kotlin/pull/698
