### ISSUE TITLE
Invalid syntax error on seemingly correct query

### ISSUE THREAD

**Issue by rorbech** [realm/realm-kotlin#683]
The following query https://github.com/realm/realm-kotlin/pull/650/commits/65d57fdadc2dcd48d83afcd13a9025a9325f7792#diff-6a88ff735acdb7c19b9ee8237d2aaea90cb18f97a133232f3300e912f945180eL126 failed on CI in the JVM test stage. 

CouIdn't reproduce it locally, so maybe more of an invalid underlying query pointer than an actual syntax error.

```[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-650/7/pipeline#step-360-log-636)[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-650/7/pipeline#step-360-log-637)[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-650/7/pipeline#step-360-log-638)[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-650/7/pipeline#step-360-log-639)[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-650/7/pipeline#step-360-log-640)[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-650/7/pipeline#step-360-log-641)[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-650/7/pipeline#step-360-log-642)[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-650/7/pipeline#step-360-log-643)[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-650/7/pipeline#step-360-log-644)[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-650/7/pipeline#step-360-log-645)[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-650/7/pipeline#step-360-log-646)[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-650/7/pipeline#step-360-log-647)[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-650/7/pipeline#step-360-log-648)[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-650/7/pipeline#step-360-log-649)[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-650/7/pipeline#step-360-log-650)[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-650/7/pipeline#step-360-log-651)[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-650/7/pipeline#step-360-log-652)[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-650/7/pipeline#step-360-log-653)[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-650/7/pipeline#step-360-log-654)io.realm.test.shared.SyncedRealmTests[jvm] > canSync[jvm] FAILED

java.lang.IllegalArgumentException: RealmCoreException [2]: std::exception Invalid syntax in query: [2]: std::exception
        at io.realm.internal.RealmUtilsKt.genericRealmCoreExceptionHandler(RealmUtils.kt:257)
        at io.realm.internal.query.ObjectQuery.tryCatchCoreException(ObjectQuery.kt:172)
        at io.realm.internal.query.ObjectQuery.parseQuery(ObjectQuery.kt:152)
        at io.realm.internal.query.ObjectQuery.<init>(ObjectQuery.kt:52)
        at io.realm.internal.BaseRealmImpl.query(BaseRealmImpl.kt:82)
        at io.realm.test.shared.SyncedRealmTests.canSync(SyncedRealmTests.kt:630)

Caused by:
 io.realm.internal.interop.RealmCoreOtherException: [2]: std::exception
            at app//io.realm.internal.interop.CoreErrorUtils.coreErrorAsThrowable(CoreErrorUtils.kt:26)
            at app//io.realm.internal.interop.realmcJNI.realm_query_parse(Native Method)
            at app//io.realm.internal.interop.realmc.realm_query_parse(realmc.java:600)
            at app//io.realm.internal.interop.RealmInterop.realm_query_parse(RealmInterop.kt:675)
            at app//io.realm.internal.query.ObjectQuery$parseQuery$1.invoke(ObjectQuery.kt:153)
            at app//io.realm.internal.query.ObjectQuery$parseQuery$1.invoke(ObjectQuery.kt:152)
            at app//io.realm.internal.query.ObjectQuery.tryCatchCoreException(ObjectQuery.kt:162)
            ... 4 more
```

**Comment by cmelchior** [comment]
In #731 this also happened on iOS, so it does not seem related to a single platform.

**Comment by iamsteveholmes** [comment]
For what it's worth I broke down my code into three lines:
```
val query = realm.query<RealmCharacter>("_id = $0", id)
val results = query.find()
val character = results.first()
```

It threw an exception on the first line.  I wanted to know if it was being caused by one of the other function calls but it appears to be the query method.

**Comment by rorbech** [comment]
Seems to be that we can actually have a pointer to a frozen realm without a transaction and that the this exception stems from not being able to create the read transaction when the realm has been advanced. If I open a read transaction for each frozen realm reference we create then it works. Will have to get some assistance from core team to fully grasp the details/intended operation to be able to evaluate the right way to fix this.
