### ISSUE TITLE
java.lang.ExceptionInInitializerError when running shared tests

### ISSUE THREAD

**Issue by iamsteveholmes** [realm/realm-kotlin#697]
I'm unable to run shared tests that access Realm.  It appears to be a problem with a null value for the Android RELEASE Version.  Here is the stacktrace:
```
java.lang.ExceptionInInitializerError
	at io.realm.RealmConfiguration$Builder.build(RealmConfiguration.kt:61)
	at io.realm.RealmConfiguration$Companion.with(RealmConfiguration.kt:85)
	at com.example.realmtest.Repository.<init>(Repository.kt:14)
	at com.example.realmtest.Repository.<init>(Repository.kt:7)
	at com.example.realmtest.RepositoryTest.<init>(RepositoryTest.kt:8)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:217)
	at org.junit.runners.BlockJUnit4ClassRunner$1.runReflectiveCall(BlockJUnit4ClassRunner.java:266)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
Caused by: java.lang.NullPointerException: RELEASE must not be null
	at io.realm.internal.platform.SystemUtilsAndroidKt.<clinit>(SystemUtilsAndroid.kt:8)
	... 44 more
```
I set up a minimal project here:

https://github.com/iamsteveholmes/RealmTest

You'll find a `Book` RealmObject class along with a `Repository` that queries the data.  The test is `RepositoryTest`.

**Comment by iamsteveholmes** [comment]
If I run `./gradlew :shared:ios64Test` or the simulator it appears to build successfully but I don't get a report...

**Comment by nhachicha** [comment]
Hi @iamsteveholmes I think this is related to https://youtrack.jetbrains.com/issue/KT-46452 where the tests under `shared/commonTets` runs without the Android runtime (i.e they don't run as instrumentation tests but rather as unit tests). You can verify it (without using Realm) just by having a test (in the shared module or in the android module `androidTest`) that prints the value of `android.os.Build.VERSION.RELEASE` it will be `null` 

A workaround could be to move these tests under the `androidApp` module and run them explicitly as instrumentation tests 
<img width="231" alt="image" src="https://user-images.githubusercontent.com/1793238/155635665-c27ac229-1423-4c99-a4c6-7f64a710ceee.png">
You can symlink these tests inside the `commonTests` module so they can also run for macOS/iOS

**Comment by iamsteveholmes** [comment]
Thank you I'll try that!

**Comment by thipokch** [comment]
@iamsteveholmes I'm facing this issue too. How did it workout for you?
