### ISSUE TITLE
Flaky test: [macos] kotlin.native.concurrent.InvalidMutabilityException: Frozen during lazy computation

### ISSUE THREAD

**Issue by rorbech** [realm/realm-kotlin#772]
This one popped up in a build after updating the changelog in https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-702/8/tests 🤔 
```
Error
kotlin.native.concurrent.InvalidMutabilityException: Frozen during lazy computation
Stacktrace
kotlin.native.concurrent.InvalidMutabilityException: Frozen during lazy computation
	at kotlin.Throwable#<init>(/Users/teamcity1/teamcity_work/6326934d18cfe24e/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/Throwable.kt:24)
	at kotlin.Exception#<init>(/Users/teamcity1/teamcity_work/6326934d18cfe24e/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/Exceptions.kt:23)
	at kotlin.RuntimeException#<init>(/Users/teamcity1/teamcity_work/6326934d18cfe24e/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/Exceptions.kt:34)
	at kotlin.native.concurrent.InvalidMutabilityException#<init>(/Users/teamcity1/teamcity_work/6326934d18cfe24e/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/native/concurrent/Freezing.kt:24)
	at kotlin.native.concurrent.SynchronizedLazyImpl#<get-value>(/Users/teamcity1/teamcity_work/6326934d18cfe24e/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/native/concurrent/Lazy.kt:145)
	at io.realm.internal.SuspendableWriter.<get-realm>#internal(/Users/realm/workspace-realm-kotlin/PR-702/packages/library-base/src/commonMain/kotlin/io/realm/internal/SuspendableWriter.kt:71)
	at io.realm.internal.SuspendableWriter.$write$lambda-3COROUTINE$153.invokeSuspend#internal(/Users/realm/workspace-realm-kotlin/PR-702/packages/library-base/src/commonMain/kotlin/io/realm/internal/SuspendableWriter.kt:106)
	at kotlin.coroutines.native.internal.BaseContinuationImpl#resumeWith(/Users/teamcity1/teamcity_work/6326934d18cfe24e/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/coroutines/ContinuationImpl.kt:30)
	at kotlinx.coroutines.DispatchedTask#run(/opt/buildAgent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/native/src/Debug.kt:17)
	at kotlinx.coroutines.EventLoopImplBase#processNextEvent(/opt/buildAgent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/common/src/EventLoop.common.kt:281)
	at kotlinx.coroutines#runEventLoop(/opt/buildAgent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/native/src/Builders.kt:87)
	at kotlinx.coroutines.WorkerCoroutineDispatcherImpl.start$lambda-0#internal(/Users/teamcity1/teamcity_work/6326934d18cfe24e/kotlin/kotlin-native/Interop/Runtime/src/native/kotlin/kotlinx/cinterop/ObjectiveCUtils.kt:20)
	at kotlinx.coroutines.WorkerCoroutineDispatcherImpl.$start$lambda-0$FUNCTION_REFERENCE$1558.invoke#internal(/opt/buildAgent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/native/src/Workers.kt:54)
	at kotlinx.coroutines.WorkerCoroutineDispatcherImpl.$start$lambda-0$FUNCTION_REFERENCE$1558.$<bridge-UNN>invoke(/opt/buildAgent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/native/src/Workers.kt:54)
	at <global>.WorkerLaunchpad(/Users/teamcity1/teamcity_work/6326934d18cfe24e/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/native/concurrent/Internal.kt:86)
	at <global>._ZN6Worker19processQueueElementEb(Unknown Source)
	at <global>._ZN12_GLOBAL__N_113workerRoutineEPv(Unknown Source)
	at <global>._pthread_start(Unknown Source)
	at <global>.thread_start(Unknown Source)
```

**Comment by cmelchior** [comment]
https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/master/382/tests

**Comment by cmelchior** [comment]
Still happens: https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/master/389/pipeline

**Comment by cmelchior** [comment]
No longer relevant since the old memory model is no longer supported.
