### ISSUE TITLE
Crash while using SNAPSHOT version with GSON

### ISSUE THREAD

**Issue by KevinBoulongne** [realm/realm-kotlin#813]
Hello,

I'm trying to use the `0.11.0-SNAPSHOT` version of the SDK.

I can build and run the app, but when I try to deserialize some JSON data, I've got a crash.

If I use the non-snapshot version _(`0.10.2`)_, everything works perfectly.

I added my `settings.gradle`, global `build.gradle` & module `build.gradle` files to show how I configured the snapshot version.

Did I do something wrong?

**Stacktrace:**

```kotlin
2022-04-28 09:03:23.291 E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-3
    Process: com.test.realmkotlin, PID: 5675
    java.lang.AssertionError: AssertionError (GSON 2.9.0): illegal type variable reference
        at com.google.gson.Gson.fromJson(Gson.java:1008)
        at com.google.gson.Gson.fromJson(Gson.java:956)
        at com.google.gson.Gson.fromJson(Gson.java:905)
        at com.test.realmkotlin.data.api.ApiRepository.getMailboxes(ApiRepository.kt:406)
        at com.test.realmkotlin.data.cache.MailRealm.getMailboxes(MailRealm.kt:55)
        at com.test.realmkotlin.ui.main.TestRealmViewModel.testRealm(TestRealmViewModel.kt:61)
        at com.test.realmkotlin.ui.main.MainActivity$onCreate$1$1.invokeSuspend(MainActivity.kt:40)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
     Caused by: java.lang.AssertionError: illegal type variable reference
        at libcore.reflect.TypeVariableImpl.resolve(TypeVariableImpl.java:111)
        at libcore.reflect.TypeVariableImpl.getGenericDeclaration(TypeVariableImpl.java:125)
        at libcore.reflect.TypeVariableImpl.hashCode(TypeVariableImpl.java:47)
        at java.util.HashMap.hash(HashMap.java:338)
        at java.util.HashMap.get(HashMap.java:556)
        at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:353)
        at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:396)
        at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:343)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:159)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:101)
        at com.google.gson.Gson.getAdapter(Gson.java:501)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(CollectionTypeAdapterFactory.java:53)
        at com.google.gson.Gson.getAdapter(Gson.java:501)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:116)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:165)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:101)
        at com.google.gson.Gson.getAdapter(Gson.java:501)
        at com.google.gson.Gson.fromJson(Gson.java:990)
        at com.google.gson.Gson.fromJson(Gson.java:956) 
        at com.google.gson.Gson.fromJson(Gson.java:905) 
        at com.test.realmkotlin.data.api.ApiRepository.getMailboxes(ApiRepository.kt:406) 
        at com.test.realmkotlin.data.cache.MailRealm.getMailboxes(MailRealm.kt:55) 
        at com.test.realmkotlin.ui.main.TestRealmViewModel.testRealm(TestRealmViewModel.kt:61) 
        at com.test.realmkotlin.ui.main.MainActivity$onCreate$1$1.invokeSuspend(MainActivity.kt:40) 
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) 
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) 
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39) 
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665) 
```

**settings.gradle:**

```gradle
pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
        maven { url 'https://oss.sonatype.org/content/repositories/snapshots' } // Realm Kotlin SNAPSHOT
    }
}

rootProject.name = 'realmkotlin'
include ':app'
```

**Global build.gradle:**

```gradle
buildscript {
    ext.gradle_version = '7.1.3'
    ext.kotlin_version = '1.6.20'
    ext.realm_kotlin_version = '0.11.0-SNAPSHOT' // Realm Kotlin SNAPSHOT
    ext.navigation_version = '2.4.2'
    ext.java_version = JavaVersion.VERSION_1_8

    repositories { maven { url 'https://oss.sonatype.org/content/repositories/snapshots' } } // Realm Kotlin SNAPSHOT
    dependencies { classpath "io.realm.kotlin:gradle-plugin:$realm_kotlin_version" } // Realm Kotlin SNAPSHOT
}

plugins {
    id 'com.android.application' version "$gradle_version" apply false
    id 'com.android.library' version "$gradle_version" apply false
    id 'org.jetbrains.kotlin.android' version "$kotlin_version" apply false
}

task clean(type: Delete) { delete rootProject.buildDir }
```

**Module build.gradle:**

```gradle
plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

configurations.all { resolutionStrategy.cacheChangingModulesFor 0, 'seconds' } // Realm Kotlin SNAPSHOT
apply plugin: "io.realm.kotlin" // Realm Kotlin SNAPSHOT

android {
    compileSdk 32

    defaultConfig {
        applicationId 'com.test.realmkotlin'
        minSdk 24
        targetSdk 32
        versionCode 1
        versionName '1.0'
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility rootProject.ext.java_version
        targetCompatibility rootProject.ext.java_version
    }

    kotlinOptions { jvmTarget = rootProject.ext.java_version }

    buildFeatures { viewBinding true }
}

dependencies {
    implementation "io.realm.kotlin:library-base:$rootProject.ext.realm_kotlin_version" // Realm Kotlin SNAPSHOT

    androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'
}
```

**Comment by cmelchior** [comment]
Hi @KevinBoulongne We have refactored some of the internals, and if I remember correctly GSON uses reflection when deserializing model classes which also caused problems in Realm Java.

Do you have some sample code of where it crashes? and the model class it is having problems with?

**Comment by KevinBoulongne** [comment]
Hi @cmelchior,
Thanks for the quick answer!

You can clone this repository _(with its submodules)_.
The command to clone with submodules is: `git clone --recurse-submodules git@github.com:Infomaniak/android-mail.git`

You can then checkout the branch `realm-snapshot`, and just build the app module.

You'll see a button, just click it, it will simulate an API call that will make the app crash.

In the `ApiController` file, line 149, you'll find the response JSON.
This JSON works perfectly fine with the `0.10.2` version of the RealmKotlin SDK.

The model class it tries to deserialize to is the `Mailbox` class.

**Comment by cmelchior** [comment]
Hi @KevinBoulongne Thanks for the hint, I'm taking a look.

**Comment by cmelchior** [comment]
I can reproduce the issue in your repo. Thanks for that 👍 

I'm still a bit unsure about the root cause as the GSON errors are a bit hard to track , but I suspect it is related to GSON not being able to fully parse one of our types.

Looking at the debugger I see this:

![image](https://user-images.githubusercontent.com/406066/166209355-8bef5705-3b5b-438e-a5dc-e870f305186f.png)

Our compiler plugin are injecting some hidden fields into the model and prefix them with `io_realm_kotlin_`. We use them for internal bookkeeping when handling managed objects. We just refactored these for 0.11.0, so most likely we did it in a way that now makes GSON unhappy.

I suspect a work-around would be to configure an appropriate ExclusionStrategy similar to what is seen here (not that exact one): https://stackoverflow.com/questions/35310688/using-realm-with-gson

But I need to dig a bit further to fully understand what is happening.

**Comment by cmelchior** [comment]
This should fix the issues:

```
    var gson: Gson = GsonBuilder()
        .registerTypeAdapter(Date::class.java, CustomDateTypeAdapter())
        .setExclusionStrategies(object: ExclusionStrategy {
            override fun shouldSkipField(f: FieldAttributes?): Boolean =
                f?.name?.startsWith("io_realm_kotlin_") ?: false
            override fun shouldSkipClass(clazz: Class<*>?): Boolean =
                false
        })
        .create()
```

I suspect GSON is having issues with our internal class, this one: https://github.com/realm/realm-kotlin/blob/master/packages/library-base/src/commonMain/kotlin/io/realm/internal/RealmObjectReference.kt#L44, but ignoring it should be perfectly fine.

**Comment by KevinBoulongne** [comment]
It works! Thanks a lot :)
