### ISSUE TITLE
Broken tests on CI: io.realm.test.shared.SyncedRealmTests

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-kotlin#814]
This test seems to fail consistently on CI only: 
https://ci.realm.io/job/realm/job/realm-kotlin/job/PR-800/19/consoleFull

Attempting to reproduce locally has failed so far.

In order to prevent us from being completely blocked, I have disabled the test, but we should do a more in-depth investigation.

Right now my only hypothesis is either Ktor acting up on the server or some weirdness with coroutines and channels

**Comment by cmelchior** [comment]
Some more observations. This seems to be a broader issue with our test setup

- `master` seems to be stable and not affected by this, only PR's.
- After disabling `testErrorHandler`, now `canSync` started failing https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-796/10/pipeline/
- It seems to only be our `TestApp` that fails, but it can either be calls towards the Admin API or normal Service calls.

**Comment by cmelchior** [comment]
Another theory, maybe related to https://github.com/realm/realm-kotlin/issues/733...and us leaking dispatchers between tests.

**Comment by cmelchior** [comment]
If I run single classes from Android Studio, everything works, but if I run `./gradlew :sync:macosTest` from the command line I  also see a lot of HttpTimeouts as on CI, but they happen in other locations, but it could point to a resource problem somehow.

**Comment by cmelchior** [comment]
Setting:

```
        engine {
            this.threadsCount = 1 // Default is 4
        }
```

Did no make a difference either.

**Comment by cmelchior** [comment]
I can reproduce the behaviour with a much simpler test (also in Android Studio):

```
    @Test
    fun stressTest() {
        for (i: Int in 0 until 100) {
            println("Iteration $i")
            val app = TestApp()
            runBlocking {
                val (email, password) = TestHelper.randomEmail() to "123456"
                app.emailPasswordAuth.registerUser(email, password)
                app.login(Credentials.emailPassword(email, password))
            }
            app.close()
        }
    }
```

It fails at Iteration 28 with:

```
io.realm.mongodb.exceptions.ConnectionException: [Custom][Interrupted(1001)] io.ktor.client.features.HttpRequestTimeoutException: Request timeout has expired [url=http://127.0.0.1:9090/api/client/v2.0/app/testapp1-aroxo/location, request_timeout=15000 ms].
io.realm.mongodb.exceptions.ConnectionException: [Custom][Interrupted(1001)] io.ktor.client.features.HttpRequestTimeoutException: Request timeout has expired [url=http://127.0.0.1:9090/api/client/v2.0/app/testapp1-aroxo/location, request_timeout=15000 ms].
	at kotlin.Throwable#<init>(/Users/teamcity1/teamcity_work/6326934d18cfe24e/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/Throwable.kt:24)
	at kotlin.Exception#<init>(/Users/teamcity1/teamcity_work/6326934d18cfe24e/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/Exceptions.kt:23)
	at kotlin.RuntimeException#<init>(/Users/teamcity1/teamcity_work/6326934d18cfe24e/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/Exceptions.kt:34)
	at io.realm.exceptions.RealmException#<init>(/Users/cm/Realm/realm-kotlin/packages/library-base/src/commonMain/kotlin/io/realm/exceptions/RealmException.kt:12)
	at io.realm.mongodb.exceptions.AppException#<init>(/Users/cm/Realm/realm-kotlin/packages/library-sync/src/commonMain/kotlin/io/realm/mongodb/exceptions/AppException.kt:96)
	at io.realm.mongodb.exceptions.ServiceException#<init>(/Users/cm/Realm/realm-kotlin/packages/library-sync/src/commonMain/kotlin/io/realm/mongodb/exceptions/ServiceExceptions.kt:33)
	at io.realm.mongodb.exceptions.ConnectionException#<init>(/Users/cm/Realm/realm-kotlin/packages/library-sync/src/commonMain/kotlin/io/realm/mongodb/exceptions/ServiceExceptions.kt:50)
	at io.realm.mongodb.internal#convertAppError(/Users/cm/Realm/realm-kotlin/packages/library-sync/src/commonMain/kotlin/io/realm/mongodb/internal/RealmSyncUtils.kt:110)
	at io.realm.mongodb.internal.object-1.onError#internal(/Users/cm/Realm/realm-kotlin/packages/library-sync/src/commonMain/kotlin/io/realm/mongodb/internal/RealmSyncUtils.kt:39)
	at io.realm.internal.interop.RealmInterop.handleAppCallback#internal(/Users/cm/Realm/realm-kotlin/packages/cinterop/src/darwin/kotlin/io/realm/internal/interop/RealmInterop.kt:1971)
	at io.realm.internal.interop.RealmInterop.realm_app_email_password_provider_client_register_email$<anonymous>_3#internal(/Users/cm/Realm/realm-kotlin/packages/cinterop/src/darwin/kotlin/io/realm/internal/interop/RealmInterop.kt:1711)
	at <global>._696f2e7265616c6d2e6b6f746c696e3a63696e7465726f70_knbridge378(/Users/cm/Realm/realm-kotlin/packages/cinterop/src/darwin/kotlin/io/realm/internal/interop/RealmInterop.kt:1712)
	at <global>._ZN5realm4util14UniqueFunctionIFvNS0_8OptionalINS_3app8AppErrorEEEEE12SpecificImplIZNS_5c_apiL13make_callbackEPFvPvPK15realm_app_errorESA_PFvSA_EEUlS5_E_E4callEOS5_(Unknown Source)
	at <global>._ZN5realm4util14UniqueFunctionIFvRKNS_3app8ResponseEEE12SpecificImplIZN12_GLOBAL__N_123handle_default_responseEONS1_IFvNS0_8OptionalINS2_8AppErrorEEEEEEE3$_0E4callES5_(Unknown Source)
	at <global>._ZN5realm4util14UniqueFunctionIFvRKNS_3app8ResponseEEE12SpecificImplIZNS2_3App17init_app_metadataEONS1_IFvRKNS0_8OptionalIS3_EEEEEE3$_7E4callES5_(Unknown Source)
	at <global>.realm_http_transport_complete_request(Unknown Source)
	at io.realm.internal.interop.RealmInterop.<init>$lambda-0$<anonymous>_19_24#internal(/Users/teamcity1/teamcity_work/6326934d18cfe24e/kotlin/kotlin-native/Interop/Runtime/src/main/kotlin/kotlinx/cinterop/Utils.kt:636)
	at io.realm.internal.interop.RealmInterop.$<init>$lambda-0$<anonymous>_19_24$FUNCTION_REFERENCE$235.response#internal(/Users/cm/Realm/realm-kotlin/packages/cinterop/src/darwin/kotlin/io/realm/internal/interop/RealmInterop.kt:2027)
	at io.realm.mongodb.internal.KtorNetworkTransport.$sendRequest$lambda-2COROUTINE$96.invokeSuspend#internal(/Users/cm/Realm/realm-kotlin/packages/library-sync/src/commonMain/kotlin/io/realm/mongodb/internal/KtorNetworkTransport.kt:128)
	at kotlin.coroutines.native.internal.BaseContinuationImpl#resumeWith(/Users/teamcity1/teamcity_work/6326934d18cfe24e/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/coroutines/ContinuationImpl.kt:30)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith#internal(/Users/administrator/Documents/agent/work/8d547b974a7be21f/ktor-utils/common/src/io/ktor/util/pipeline/SuspendFunctionGun.kt:193)
	at io.ktor.util.pipeline.SuspendFunctionGun.object-1.resumeWith#internal(/Users/administrator/Documents/agent/work/8d547b974a7be21f/ktor-utils/common/src/io/ktor/util/pipeline/SuspendFunctionGun.kt:89)
	at kotlin.coroutines.native.internal.BaseContinuationImpl#resumeWith(/Users/teamcity1/teamcity_work/6326934d18cfe24e/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/coroutines/ContinuationImpl.kt:43)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith#internal(/Users/administrator/Documents/agent/work/8d547b974a7be21f/ktor-utils/common/src/io/ktor/util/pipeline/SuspendFunctionGun.kt:193)
	at io.ktor.util.pipeline.SuspendFunctionGun.object-1.resumeWith#internal(/Users/administrator/Documents/agent/work/8d547b974a7be21f/ktor-utils/common/src/io/ktor/util/pipeline/SuspendFunctionGun.kt:89)
	at kotlin.coroutines.native.internal.BaseContinuationImpl#resumeWith(/Users/teamcity1/teamcity_work/6326934d18cfe24e/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/coroutines/ContinuationImpl.kt:43)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith#internal(/Users/administrator/Documents/agent/work/8d547b974a7be21f/ktor-utils/common/src/io/ktor/util/pipeline/SuspendFunctionGun.kt:193)
	at io.ktor.util.pipeline.SuspendFunctionGun.object-1.resumeWith#internal(/Users/administrator/Documents/agent/work/8d547b974a7be21f/ktor-utils/common/src/io/ktor/util/pipeline/SuspendFunctionGun.kt:89)
	at kotlin.coroutines.native.internal.BaseContinuationImpl#resumeWith(/Users/teamcity1/teamcity_work/6326934d18cfe24e/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/coroutines/ContinuationImpl.kt:43)
```

**Comment by cmelchior** [comment]
```
    @Test
    fun stressTest() {
        for (i: Int in 0 until 100) {
            println("Iteration $i")
            val app = TestApp()
            app.close()
        }
    }
```

Also fails consistently, while this does not:

````
  @Test
  fun stressTestJustGet() {
      for (i: Int in 0 until 1000) {
          println("Iteration $i")
          runBlocking(singleThreadDispatcher("test-app-dispatcher")) {
              TestApp.getAppId(TEST_APP_1, false)
          }
      }
  }
```

**Comment by cmelchior** [comment]
Another theory:

- Right now we are creating HttpClient's for every request, which was a supposed work-around for https://github.com/realm/realm-kotlin/issues/480, while in reality it was probably caused by https://youtrack.jetbrains.com/issue/KTOR-4101/JsonFeature:-HttpClient-always-timeout-when-sending-PATCH-reques

I was attempting to reuse the HttpClient _and_ closing it and it seems it allow the tests to run for much longer before starting to time out, so a guess could be that HttpClients actually have som underlying shared resource and if they are not closed correctly, that resource eventually runs out.
