### ISSUE TITLE
RELEASE must not be null. Caused by: java.lang.NullPointerException

### ISSUE THREAD

**Issue by XandrMaster** [realm/realm-kotlin#917]
Hello guys . Looks like another issue if common test launched for Android . For iOs looks good .
take a look to this Exception pls:

`java.lang.ExceptionInInitializerError
	at io.realm.kotlin.RealmConfiguration$Builder.<init>(RealmConfiguration.kt:54)
	at com.example.realmtest.Repository.<init>(Repository.kt:13)
	at com.example.realmtest.Repository.<init>(Repository.kt:6)
	at com.example.realmtest.RepositoryTest.<init>(RepositoryTest.kt:8)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:250)
	at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:260)
	at org.junit.runners.BlockJUnit4ClassRunner$2.runReflectiveCall(BlockJUnit4ClassRunner.java:309)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
Caused by: java.lang.NullPointerException: RELEASE must not be null
	at io.realm.kotlin.internal.platform.SystemUtilsAndroidKt.<clinit>(SystemUtilsAndroid.kt:8)
	... 47 more
`

For reproduce that exception just [lunch following test function](https://github.com/XandrMaster/RealmTest/blob/main/shared/src/commonTest/kotlin/com/example/realmtest/RepositoryTest.kt#L11) in my small demo project

**Comment by edualonso** [comment]
Hi @XandrMaster.

The crash you are experiencing is not caused by Realm per se, but is happening because a Realm function is not able to find the value for `android.os.Build.VERSION.RELEASE`. This value is used internally by Realm and we expect it not to be null. However, this value is obtained by calling `getString("ro.build.version.release")` which is a value only present on Android devices or emulators. This means that the value returned by this call will be null since your test is being executed as a JVM test and not an Android test, which is expected and thus you see this crash.

To avoid this you need to configure your project to run your tests on an Android emulator/device by modifying your `shared` module `build.gradle.kts` script:

Modify the `kotlin` block to look like this:
```
kotlin {

    // ...

    sourceSets {
        // ...

        // Remove these two lines and replace with the code below
//        val androidMain by getting
//        val androidTest by getting

        getByName("androidMain") {
            kotlin.srcDir("src/androidMain/kotlin")
        }
        getByName("androidTest") {
            dependencies {
                implementation(kotlin("test"))
                implementation(kotlin("test-junit"))
                implementation("junit:junit:4.13.2")
            }
        }

        // ...
    }
}
```

Modify the `android` block to look like this:
```
android {
    // ...

    defaultConfig {
        // ...

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"

        sourceSets {
            getByName("main") {
                manifest.srcFile("src/androidMain/AndroidManifest.xml")
                getByName("androidTest") {
                    java.srcDirs("src/androidTest/kotlin")
                }
            }
        }
    }
    dependencies {
        testImplementation("junit:junit:4.13.2")
        androidTestImplementation("androidx.test.ext:junit:1.1.3")
        androidTestImplementation("androidx.test.espresso:espresso-core:3.4.0")
    }
}
```

**Comment by XandrMaster** [comment]
1. But if the tests source code for Realm the same for Android and iOs platform I should duplicate the same classes for androidApp and iOsApp instead of just keep single test class in shared folder ? 
2. It doesn't help , the same issue `RELEASE must not be null` , take a look to my [latest commit ](https://github.com/iamsteveholmes/RealmTest.git)

**Comment by XandrMaster** [comment]
So since you are using this line of code `public actual val OS_VERSION: String = android.os.Build.VERSION.RELEASE`  in `SystemUtilsAndroid.kt` file we have no any chance test Realm in commonTest , only in androidTest with device or emulator environment , right ?

**Comment by cmelchior** [comment]
Yes, that is correct. We reported the issue to JetBrains here: https://youtrack.jetbrains.com/issue/KT-46452/Allow-to-run-common-tests-as-Android-Instrumentation-tests

**Comment by MirzaShadman** [comment]
> Yes, that is correct. We reported the issue to JetBrains here: https://youtrack.jetbrains.com/issue/KT-46452/Allow-to-run-common-tests-as-Android-Instrumentation-tests

@cmelchior Is there a way we can check the coverage of androidTest folder because in our project we are able to measure comonTest folder test cases but not of androidTest folder.

**Comment by cmelchior** [comment]
@MirzaShadman You mean using jacoco or similar? We are seeing reports that this is causing problems on some versions of the Android Gradle Plugin. What version of AGP are you using and how do you want to measure the test coverage?

**Comment by MirzaShadman** [comment]
@cmelchior yes, we are using kover for this, but jacoco is also fine. AGP version -> 7.1.3. What I meant we are able to see the coverage report for commonTest folder in CI but we have many test cases inside androidTest folder of our kmm project which we are commenting and pushing into CI to make the build successful. So Is there anyway to see coverage for androidTest test cases ? even if it is possible locally like how we do for commonTest folder -> right click and do "run with coverage" option in android studio.
