### ISSUE TITLE
Flaky test: NonLatinTests.readNullCharacterFromMongoDB [JVM]

### ISSUE THREAD

**Issue by edualonso** [realm/realm-kotlin#918]
Seen in a https://github.com/realm/realm-kotlin/pull/913, build https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-913/8/pipeline/#step-370-log-1050

```
io.realm.kotlin.test.mongodb.shared.nonlatin.NonLatinTests[jvm] > readNullCharacterFromMongoDB[jvm] FAILED
    org.junit.ComparisonFailure: expected:<foo[bar]> but was:<foo[]>
        at org.junit.Assert.assertEquals(Assert.java:115)
        at kotlin.test.junit.JUnitAsserter.assertEquals(JUnitSupport.kt:32)
        at kotlin.test.AssertionsKt__AssertionsKt.assertEquals(Assertions.kt:63)
        at kotlin.test.AssertionsKt.assertEquals(Unknown Source)
        at kotlin.test.AssertionsKt__AssertionsKt.assertEquals$default(Assertions.kt:62)
        at kotlin.test.AssertionsKt.assertEquals$default(Unknown Source)
        at io.realm.kotlin.test.mongodb.shared.nonlatin.NonLatinTests$readNullCharacterFromMongoDB$1.invokeSuspend(NonLatinTests.kt:86)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:281)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:87)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:61)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at io.realm.kotlin.internal.platform.CoroutineUtilsSharedJvmKt.runBlocking(CoroutineUtilsSharedJvm.kt:13)
        at io.realm.kotlin.internal.platform.CoroutineUtilsSharedJvmKt.runBlocking$default(CoroutineUtilsSharedJvm.kt:12)
        at io.realm.kotlin.test.mongodb.shared.nonlatin.NonLatinTests.readNullCharacterFromMongoDB(NonLatinTests.kt:54)
```

**Comment by cmelchior** [comment]
Seems to have gone away
