### ISSUE TITLE
Suspend functions error handling

### ISSUE THREAD

**Issue by sheinin** [realm/realm-kotlin#954]
This exception occurs when the app is started with Internet switched off

`
1659747208.324 W: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
1659747208.324 W: SLF4J: Defaulting to no-operation (NOP) logger implementation
1659747208.324 W: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
1659747208.376 D: Shutting down VM
1659747208.377 E: FATAL EXCEPTION: main
    Process: com.nearmeentertainment.vegasnearme, PID: 22199
    io.realm.kotlin.mongodb.exceptions.ConnectionException: [Custom][Unknown(1002)] java.nio.channels.UnresolvedAddressException.
        at io.realm.kotlin.mongodb.internal.RealmSyncUtilsKt.convertAppError(RealmSyncUtils.kt:120)
        at io.realm.kotlin.mongodb.internal.RealmSyncUtilsKt$channelResultCallback$1.onError(RealmSyncUtils.kt:40)
        at io.realm.kotlin.internal.interop.realmcJNI.complete_http_request(Native Method)
        at io.realm.kotlin.internal.interop.realmc.complete_http_request(realmc.java:1469)
        at io.realm.kotlin.internal.interop.sync.ResponseCallbackImpl.response(ResponseCallbackImpl.kt:26)
        at io.realm.kotlin.mongodb.internal.KtorNetworkTransport$sendRequest$1.invokeSuspend(KtorNetworkTransport.kt:125)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:194)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:15)
        at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:89)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:194)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:15)
        at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:89)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:194)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:15)
        at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:89)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:194)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:15)
        at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:89)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:194)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:15)
        at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:89)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:241)
        at android.os.Looper.loop(Looper.java:358)
        at android.os.HandlerThread.run(HandlerThread.java:67)
1659747208.381 I: Sending signal. PID: 22199 SIG: 9
`

**Comment by cmelchior** [comment]
Hi @sheinin This is normal coroutine behavior. `io.realm.kotlin.mongodb.exceptions.ConnectionException: [Custom][Unknown(1002)]` is an uncaught exception thrown by the Realm API when calling a suspend function...mostly likely `App.login()`

We should have noted which exceptions our suspend functions can throw.

But you can read more about error handling here:

https://kotlinlang.org/docs/exception-handling.html#cancellation-and-exceptions
https://hossainkhan.medium.com/kotlin-coroutines-error-handling-strategy-runcatching-and-result-class-14e1467ced6

**Comment by sheinin** [comment]
Sorted it out with `runCatching {}`
