### ISSUE TITLE
Flaky test - RealmTests.coroutineCancelCausesRollback

### ISSUE THREAD

**Issue by edualonso** [realm/realm-kotlin#987]
Seen in master on Android: https://ci.realm.io/job/realm/job/realm-kotlin/job/master/469/testReport/junit/io.realm.kotlin.test.shared/RealmTests/coroutineCancelCausesRollback/

```
java.lang.AssertionError: expected:<0> but was:<1>
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.failNotEquals(Assert.java:835)
at org.junit.Assert.assertEquals(Assert.java:120)
at kotlin.test.junit.JUnitAsserter.assertEquals(JUnitSupport.kt:32)
at kotlin.test.AssertionsKt__AssertionsKt.assertEquals(Assertions.kt:63)
at kotlin.test.AssertionsKt.assertEquals(Unknown Source:1)
at kotlin.test.AssertionsKt__AssertionsKt.assertEquals$default(Assertions.kt:62)
at kotlin.test.AssertionsKt.assertEquals$default(Unknown Source:1)
at io.realm.kotlin.test.shared.RealmTests$coroutineCancelCausesRollback$1.invokeSuspend(RealmTests.kt:363)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:281)
at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:87)
at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:61)
at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:40)
at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
at io.realm.kotlin.test.shared.RealmTests.coroutineCancelCausesRollback(RealmTests.kt:340)
```

**Comment by cmelchior** [comment]
Seems to have gone away
